// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/reward/v1/reward.proto (package ecopoint.reward.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Decimal } from "../../common/v1/common_pb.js";

/**
 * @generated from enum ecopoint.reward.v1.RedemptionStatus
 */
export enum RedemptionStatus {
  /**
   * @generated from enum value: REDEMPTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REDEMPTION_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: REDEMPTION_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * @generated from enum value: REDEMPTION_STATUS_CANCELLED = 3;
   */
  CANCELLED = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(RedemptionStatus)
proto3.util.setEnumType(RedemptionStatus, "ecopoint.reward.v1.RedemptionStatus", [
  { no: 0, name: "REDEMPTION_STATUS_UNSPECIFIED" },
  { no: 1, name: "REDEMPTION_STATUS_PENDING" },
  { no: 2, name: "REDEMPTION_STATUS_COMPLETED" },
  { no: 3, name: "REDEMPTION_STATUS_CANCELLED" },
]);

/**
 * @generated from message ecopoint.reward.v1.Voucher
 */
export class Voucher extends Message<Voucher> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string code = 2;
   */
  code = "";

  /**
   * @generated from field: string title = 3;
   */
  title = "";

  /**
   * @generated from field: string description = 4;
   */
  description = "";

  /**
   * @generated from field: ecopoint.common.v1.Decimal point_cost = 5;
   */
  pointCost?: Decimal;

  /**
   * @generated from field: int32 stock = 6;
   */
  stock = 0;

  /**
   * @generated from field: bool is_active = 7;
   */
  isActive = false;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Voucher>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.Voucher";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "point_cost", kind: "message", T: Decimal },
    { no: 6, name: "stock", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Voucher {
    return new Voucher().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Voucher {
    return new Voucher().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Voucher {
    return new Voucher().fromJsonString(jsonString, options);
  }

  static equals(a: Voucher | PlainMessage<Voucher> | undefined, b: Voucher | PlainMessage<Voucher> | undefined): boolean {
    return proto3.util.equals(Voucher, a, b);
  }
}

/**
 * @generated from message ecopoint.reward.v1.ListVouchersRequest
 */
export class ListVouchersRequest extends Message<ListVouchersRequest> {
  /**
   * Bỏ trống = tất cả active. Set true/false để filter rõ.
   *
   * @generated from field: bool only_active = 1;
   */
  onlyActive = false;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListVouchersRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.ListVouchersRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "only_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListVouchersRequest {
    return new ListVouchersRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListVouchersRequest {
    return new ListVouchersRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListVouchersRequest {
    return new ListVouchersRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListVouchersRequest | PlainMessage<ListVouchersRequest> | undefined, b: ListVouchersRequest | PlainMessage<ListVouchersRequest> | undefined): boolean {
    return proto3.util.equals(ListVouchersRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.reward.v1.ListVouchersResponse
 */
export class ListVouchersResponse extends Message<ListVouchersResponse> {
  /**
   * @generated from field: repeated ecopoint.reward.v1.Voucher vouchers = 1;
   */
  vouchers: Voucher[] = [];

  constructor(data?: PartialMessage<ListVouchersResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.ListVouchersResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "vouchers", kind: "message", T: Voucher, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListVouchersResponse {
    return new ListVouchersResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListVouchersResponse {
    return new ListVouchersResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListVouchersResponse {
    return new ListVouchersResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListVouchersResponse | PlainMessage<ListVouchersResponse> | undefined, b: ListVouchersResponse | PlainMessage<ListVouchersResponse> | undefined): boolean {
    return proto3.util.equals(ListVouchersResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.reward.v1.Redemption
 */
export class Redemption extends Message<Redemption> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string voucher_id = 2;
   */
  voucherId = "";

  /**
   * @generated from field: string user_id = 3;
   */
  userId = "";

  /**
   * @generated from field: ecopoint.common.v1.Decimal point_cost = 4;
   */
  pointCost?: Decimal;

  /**
   * @generated from field: ecopoint.reward.v1.RedemptionStatus status = 5;
   */
  status = RedemptionStatus.UNSPECIFIED;

  /**
   * @generated from field: string point_tx_id = 6;
   */
  pointTxId = "";

  /**
   * @generated from field: string failure_reason = 7;
   */
  failureReason = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 9;
   */
  completedAt?: Timestamp;

  constructor(data?: PartialMessage<Redemption>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.Redemption";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "voucher_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "point_cost", kind: "message", T: Decimal },
    { no: 5, name: "status", kind: "enum", T: proto3.getEnumType(RedemptionStatus) },
    { no: 6, name: "point_tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "failure_reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
    { no: 9, name: "completed_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Redemption {
    return new Redemption().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Redemption {
    return new Redemption().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Redemption {
    return new Redemption().fromJsonString(jsonString, options);
  }

  static equals(a: Redemption | PlainMessage<Redemption> | undefined, b: Redemption | PlainMessage<Redemption> | undefined): boolean {
    return proto3.util.equals(Redemption, a, b);
  }
}

/**
 * @generated from message ecopoint.reward.v1.RedeemVoucherRequest
 */
export class RedeemVoucherRequest extends Message<RedeemVoucherRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: string voucher_id = 2;
   */
  voucherId = "";

  /**
   * Bắt buộc — chống double-redeem khi client retry.
   *
   * @generated from field: string idempotency_key = 3;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<RedeemVoucherRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.RedeemVoucherRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "voucher_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RedeemVoucherRequest {
    return new RedeemVoucherRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RedeemVoucherRequest {
    return new RedeemVoucherRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RedeemVoucherRequest {
    return new RedeemVoucherRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RedeemVoucherRequest | PlainMessage<RedeemVoucherRequest> | undefined, b: RedeemVoucherRequest | PlainMessage<RedeemVoucherRequest> | undefined): boolean {
    return proto3.util.equals(RedeemVoucherRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.reward.v1.RedeemVoucherResponse
 */
export class RedeemVoucherResponse extends Message<RedeemVoucherResponse> {
  /**
   * @generated from field: ecopoint.reward.v1.Redemption redemption = 1;
   */
  redemption?: Redemption;

  /**
   * Số dư sau khi trừ điểm (lấy từ Point Service).
   *
   * @generated from field: ecopoint.common.v1.Decimal new_balance = 2;
   */
  newBalance?: Decimal;

  constructor(data?: PartialMessage<RedeemVoucherResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.reward.v1.RedeemVoucherResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "redemption", kind: "message", T: Redemption },
    { no: 2, name: "new_balance", kind: "message", T: Decimal },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RedeemVoucherResponse {
    return new RedeemVoucherResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RedeemVoucherResponse {
    return new RedeemVoucherResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RedeemVoucherResponse {
    return new RedeemVoucherResponse().fromJsonString(jsonString, options);
  }

  static equals(a: RedeemVoucherResponse | PlainMessage<RedeemVoucherResponse> | undefined, b: RedeemVoucherResponse | PlainMessage<RedeemVoucherResponse> | undefined): boolean {
    return proto3.util.equals(RedeemVoucherResponse, a, b);
  }
}

