// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/reward/v1/reward.proto (package ecopoint.reward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RedeemVoucherRequest, RedeemVoucherResponse } from "./reward_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.reward.v1.RewardService
 */
export const RewardService = {
  typeName: "ecopoint.reward.v1.RewardService",
  methods: {
    /**
     * @generated from rpc ecopoint.reward.v1.RewardService.RedeemVoucher
     */
    redeemVoucher: {
      name: "RedeemVoucher",
      I: RedeemVoucherRequest,
      O: RedeemVoucherResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

