// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package bookingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    customer_id, address, location, estimated_kg, note, scheduled_at
) VALUES (
    $1,
    $2,
    ST_SetSRID(ST_MakePoint($3, $4), 4326),
    $5, $6, $7
)
RETURNING
    id,
    customer_id,
    collector_id,
    status,
    address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg,
    note,
    scheduled_at,
    created_at,
    updated_at
`

type CreateBookingParams struct {
	CustomerID    pgtype.UUID        `json:"customer_id"`
	Address       string             `json:"address"`
	StMakepoint   interface{}        `json:"st_makepoint"`
	StMakepoint_2 interface{}        `json:"st_makepoint_2"`
	EstimatedKg   pgtype.Numeric     `json:"estimated_kg"`
	Note          *string            `json:"note"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
}

type CreateBookingRow struct {
	ID          pgtype.UUID        `json:"id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	CollectorID pgtype.UUID        `json:"collector_id"`
	Status      BookingStatus      `json:"status"`
	Address     string             `json:"address"`
	Longitude   float64            `json:"longitude"`
	Latitude    float64            `json:"latitude"`
	EstimatedKg pgtype.Numeric     `json:"estimated_kg"`
	Note        *string            `json:"note"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Truyền vào: customer_id, address, longitude, latitude, estimated_kg, note, scheduled_at.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.CustomerID,
		arg.Address,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.EstimatedKg,
		arg.Note,
		arg.ScheduledAt,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findNearestBookings = `-- name: FindNearestBookings :many
SELECT
    id,
    customer_id,
    collector_id,
    status,
    address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    ST_DistanceSphere(
        location,
        ST_SetSRID(ST_MakePoint($1, $2), 4326)
    )::float8 AS distance_m,
    estimated_kg,
    scheduled_at,
    created_at
FROM bookings
WHERE status = 'pending'
ORDER BY location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
LIMIT 5
`

type FindNearestBookingsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
}

type FindNearestBookingsRow struct {
	ID          pgtype.UUID        `json:"id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	CollectorID pgtype.UUID        `json:"collector_id"`
	Status      BookingStatus      `json:"status"`
	Address     string             `json:"address"`
	Longitude   float64            `json:"longitude"`
	Latitude    float64            `json:"latitude"`
	DistanceM   float64            `json:"distance_m"`
	EstimatedKg pgtype.Numeric     `json:"estimated_kg"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Tìm 5 booking 'pending' gần nhất với toạ độ ($1 = longitude, $2 = latitude).
// Dùng toán tử KNN `<->` để tận dụng GIST index, sau đó tính khoảng cách thực tế
// bằng ST_DistanceSphere (đơn vị: mét, độ chính xác cao trên bề mặt cầu).
func (q *Queries) FindNearestBookings(ctx context.Context, arg FindNearestBookingsParams) ([]FindNearestBookingsRow, error) {
	rows, err := q.db.Query(ctx, findNearestBookings, arg.StMakepoint, arg.StMakepoint_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearestBookingsRow{}
	for rows.Next() {
		var i FindNearestBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CollectorID,
			&i.Status,
			&i.Address,
			&i.Longitude,
			&i.Latitude,
			&i.DistanceM,
			&i.EstimatedKg,
			&i.ScheduledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
