// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking.sql

package bookingdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptBookingByStation = `-- name: AcceptBookingByStation :one
UPDATE bookings
SET status     = 'accepted',
    station_id = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
`

type AcceptBookingByStationParams struct {
	ID        pgtype.UUID `json:"id"`
	StationID pgtype.UUID `json:"station_id"`
}

type AcceptBookingByStationRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

// Atomic reservation: chỉ chuyển PENDING → ACCEPTED khi chưa ai nhận
// (chống race 2 Vựa cùng grab 1 đơn). 0 row → bookings không thay đổi.
func (q *Queries) AcceptBookingByStation(ctx context.Context, arg AcceptBookingByStationParams) (AcceptBookingByStationRow, error) {
	row := q.db.QueryRow(ctx, acceptBookingByStation, arg.ID, arg.StationID)
	var i AcceptBookingByStationRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
	)
	return i, err
}

const collectorVerifyCancelled = `-- name: CollectorVerifyCancelled :one
UPDATE bookings
SET collector_weight = $2,
    status           = 'cancelled',
    updated_at       = NOW()
WHERE id = $1 AND status = 'delivered_to_station'
RETURNING
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at,
    driver_weight, collector_weight, proof_image_url,
    user_pending_tx_id, driver_pending_tx_id
`

type CollectorVerifyCancelledParams struct {
	ID              pgtype.UUID    `json:"id"`
	CollectorWeight pgtype.Numeric `json:"collector_weight"`
}

type CollectorVerifyCancelledRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CollectorID       pgtype.UUID        `json:"collector_id"`
	Status            BookingStatus      `json:"status"`
	Address           string             `json:"address"`
	Longitude         float64            `json:"longitude"`
	Latitude          float64            `json:"latitude"`
	EstimatedKg       pgtype.Numeric     `json:"estimated_kg"`
	MaterialType      MaterialType       `json:"material_type"`
	Note              *string            `json:"note"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StationID         pgtype.UUID        `json:"station_id"`
	PinCode           *string            `json:"pin_code"`
	PinExpiredAt      pgtype.Timestamptz `json:"pin_expired_at"`
	DriverWeight      pgtype.Numeric     `json:"driver_weight"`
	CollectorWeight   pgtype.Numeric     `json:"collector_weight"`
	ProofImageUrl     *string            `json:"proof_image_url"`
	UserPendingTxID   pgtype.UUID        `json:"user_pending_tx_id"`
	DriverPendingTxID pgtype.UUID        `json:"driver_pending_tx_id"`
}

// Atomic: DELIVERED_TO_STATION → CANCELLED (gian lận).
func (q *Queries) CollectorVerifyCancelled(ctx context.Context, arg CollectorVerifyCancelledParams) (CollectorVerifyCancelledRow, error) {
	row := q.db.QueryRow(ctx, collectorVerifyCancelled, arg.ID, arg.CollectorWeight)
	var i CollectorVerifyCancelledRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
		&i.DriverWeight,
		&i.CollectorWeight,
		&i.ProofImageUrl,
		&i.UserPendingTxID,
		&i.DriverPendingTxID,
	)
	return i, err
}

const collectorVerifyReconciled = `-- name: CollectorVerifyReconciled :one

UPDATE bookings
SET collector_weight = $2,
    status           = 'reconciled',
    updated_at       = NOW()
WHERE id = $1 AND status = 'delivered_to_station'
RETURNING
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at,
    driver_weight, collector_weight, proof_image_url,
    user_pending_tx_id, driver_pending_tx_id
`

type CollectorVerifyReconciledParams struct {
	ID              pgtype.UUID    `json:"id"`
	CollectorWeight pgtype.Numeric `json:"collector_weight"`
}

type CollectorVerifyReconciledRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CollectorID       pgtype.UUID        `json:"collector_id"`
	Status            BookingStatus      `json:"status"`
	Address           string             `json:"address"`
	Longitude         float64            `json:"longitude"`
	Latitude          float64            `json:"latitude"`
	EstimatedKg       pgtype.Numeric     `json:"estimated_kg"`
	MaterialType      MaterialType       `json:"material_type"`
	Note              *string            `json:"note"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StationID         pgtype.UUID        `json:"station_id"`
	PinCode           *string            `json:"pin_code"`
	PinExpiredAt      pgtype.Timestamptz `json:"pin_expired_at"`
	DriverWeight      pgtype.Numeric     `json:"driver_weight"`
	CollectorWeight   pgtype.Numeric     `json:"collector_weight"`
	ProofImageUrl     *string            `json:"proof_image_url"`
	UserPendingTxID   pgtype.UUID        `json:"user_pending_tx_id"`
	DriverPendingTxID pgtype.UUID        `json:"driver_pending_tx_id"`
}

// ============================================================
// CollectorVerifyBooking — Vựa cân lại, đối chiếu, quyết
// ============================================================
// Atomic: DELIVERED_TO_STATION → RECONCILED, lưu collector_weight.
func (q *Queries) CollectorVerifyReconciled(ctx context.Context, arg CollectorVerifyReconciledParams) (CollectorVerifyReconciledRow, error) {
	row := q.db.QueryRow(ctx, collectorVerifyReconciled, arg.ID, arg.CollectorWeight)
	var i CollectorVerifyReconciledRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
		&i.DriverWeight,
		&i.CollectorWeight,
		&i.ProofImageUrl,
		&i.UserPendingTxID,
		&i.DriverPendingTxID,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one

INSERT INTO bookings (
    customer_id, address, location, estimated_kg, material_type,
    note, scheduled_at, pin_code, pin_expired_at
) VALUES (
    $1, $2,
    ST_SetSRID(ST_MakePoint($3, $4), 4326),
    $5, $6, $7, $8, $9, $10
)
RETURNING
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
`

type CreateBookingParams struct {
	CustomerID    pgtype.UUID        `json:"customer_id"`
	Address       string             `json:"address"`
	StMakepoint   interface{}        `json:"st_makepoint"`
	StMakepoint_2 interface{}        `json:"st_makepoint_2"`
	EstimatedKg   pgtype.Numeric     `json:"estimated_kg"`
	MaterialType  MaterialType       `json:"material_type"`
	Note          *string            `json:"note"`
	ScheduledAt   pgtype.Timestamptz `json:"scheduled_at"`
	PinCode       *string            `json:"pin_code"`
	PinExpiredAt  pgtype.Timestamptz `json:"pin_expired_at"`
}

type CreateBookingRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

// ============================================================
// Booking Service queries — V1.3
// ============================================================
// Tham số: customer_id, address, longitude, latitude, estimated_kg,
//
//	material_type, note, scheduled_at, pin_code, pin_expired_at.
//
// PIN 4-digit + TTL được generate ở app layer (crypto/rand).
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.CustomerID,
		arg.Address,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.EstimatedKg,
		arg.MaterialType,
		arg.Note,
		arg.ScheduledAt,
		arg.PinCode,
		arg.PinExpiredAt,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
	)
	return i, err
}

const driverCompleteBooking = `-- name: DriverCompleteBooking :one

UPDATE bookings
SET driver_weight    = $2,
    proof_image_url  = $3,
    collector_id     = $4,
    status           = 'delivered_to_station',
    updated_at       = NOW()
WHERE id = $1
  AND status = 'accepted'
  AND pin_code = $5
  AND pin_expired_at > NOW()
RETURNING
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at,
    driver_weight, collector_weight, proof_image_url,
    user_pending_tx_id, driver_pending_tx_id
`

type DriverCompleteBookingParams struct {
	ID            pgtype.UUID    `json:"id"`
	DriverWeight  pgtype.Numeric `json:"driver_weight"`
	ProofImageUrl *string        `json:"proof_image_url"`
	CollectorID   pgtype.UUID    `json:"collector_id"`
	PinCode       *string        `json:"pin_code"`
}

type DriverCompleteBookingRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CollectorID       pgtype.UUID        `json:"collector_id"`
	Status            BookingStatus      `json:"status"`
	Address           string             `json:"address"`
	Longitude         float64            `json:"longitude"`
	Latitude          float64            `json:"latitude"`
	EstimatedKg       pgtype.Numeric     `json:"estimated_kg"`
	MaterialType      MaterialType       `json:"material_type"`
	Note              *string            `json:"note"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StationID         pgtype.UUID        `json:"station_id"`
	PinCode           *string            `json:"pin_code"`
	PinExpiredAt      pgtype.Timestamptz `json:"pin_expired_at"`
	DriverWeight      pgtype.Numeric     `json:"driver_weight"`
	CollectorWeight   pgtype.Numeric     `json:"collector_weight"`
	ProofImageUrl     *string            `json:"proof_image_url"`
	UserPendingTxID   pgtype.UUID        `json:"user_pending_tx_id"`
	DriverPendingTxID pgtype.UUID        `json:"driver_pending_tx_id"`
}

// ============================================================
// DriverCompleteBooking — atomic PIN + TTL check + state change
// ============================================================
// Chỉ chuyển ACCEPTED → DELIVERED_TO_STATION khi:
//   - Booking thuộc trạng thái accepted
//   - PIN khớp y hệt
//   - pin_expired_at chưa quá hạn
//
// 0 row trả về = sai PIN / hết hạn / status sai → caller throw InvalidArgument.
func (q *Queries) DriverCompleteBooking(ctx context.Context, arg DriverCompleteBookingParams) (DriverCompleteBookingRow, error) {
	row := q.db.QueryRow(ctx, driverCompleteBooking,
		arg.ID,
		arg.DriverWeight,
		arg.ProofImageUrl,
		arg.CollectorID,
		arg.PinCode,
	)
	var i DriverCompleteBookingRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
		&i.DriverWeight,
		&i.CollectorWeight,
		&i.ProofImageUrl,
		&i.UserPendingTxID,
		&i.DriverPendingTxID,
	)
	return i, err
}

const findNearestBookings = `-- name: FindNearestBookings :many
SELECT
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    ST_DistanceSphere(
        location,
        ST_SetSRID(ST_MakePoint($1, $2), 4326)
    )::float8 AS distance_m,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
FROM bookings
WHERE status = 'pending'
ORDER BY location <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
LIMIT $3
`

type FindNearestBookingsParams struct {
	StMakepoint   interface{} `json:"st_makepoint"`
	StMakepoint_2 interface{} `json:"st_makepoint_2"`
	Limit         int32       `json:"limit"`
}

type FindNearestBookingsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	DistanceM    float64            `json:"distance_m"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

func (q *Queries) FindNearestBookings(ctx context.Context, arg FindNearestBookingsParams) ([]FindNearestBookingsRow, error) {
	rows, err := q.db.Query(ctx, findNearestBookings, arg.StMakepoint, arg.StMakepoint_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNearestBookingsRow{}
	for rows.Next() {
		var i FindNearestBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CollectorID,
			&i.Status,
			&i.Address,
			&i.Longitude,
			&i.Latitude,
			&i.DistanceM,
			&i.EstimatedKg,
			&i.MaterialType,
			&i.Note,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StationID,
			&i.PinCode,
			&i.PinExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at,
    driver_weight, collector_weight, proof_image_url,
    user_pending_tx_id, driver_pending_tx_id
FROM bookings
WHERE id = $1
`

type GetBookingByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	CollectorID       pgtype.UUID        `json:"collector_id"`
	Status            BookingStatus      `json:"status"`
	Address           string             `json:"address"`
	Longitude         float64            `json:"longitude"`
	Latitude          float64            `json:"latitude"`
	EstimatedKg       pgtype.Numeric     `json:"estimated_kg"`
	MaterialType      MaterialType       `json:"material_type"`
	Note              *string            `json:"note"`
	ScheduledAt       pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	StationID         pgtype.UUID        `json:"station_id"`
	PinCode           *string            `json:"pin_code"`
	PinExpiredAt      pgtype.Timestamptz `json:"pin_expired_at"`
	DriverWeight      pgtype.Numeric     `json:"driver_weight"`
	CollectorWeight   pgtype.Numeric     `json:"collector_weight"`
	ProofImageUrl     *string            `json:"proof_image_url"`
	UserPendingTxID   pgtype.UUID        `json:"user_pending_tx_id"`
	DriverPendingTxID pgtype.UUID        `json:"driver_pending_tx_id"`
}

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CollectorID,
		&i.Status,
		&i.Address,
		&i.Longitude,
		&i.Latitude,
		&i.EstimatedKg,
		&i.MaterialType,
		&i.Note,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StationID,
		&i.PinCode,
		&i.PinExpiredAt,
		&i.DriverWeight,
		&i.CollectorWeight,
		&i.ProofImageUrl,
		&i.UserPendingTxID,
		&i.DriverPendingTxID,
	)
	return i, err
}

const getStation = `-- name: GetStation :one

SELECT id, name, address, owner_id, is_active, created_at, updated_at
FROM stations
WHERE id = $1
`

type GetStationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Address   string             `json:"address"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ─── Station ──────────────────────────────────────────────────
func (q *Queries) GetStation(ctx context.Context, id pgtype.UUID) (GetStationRow, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i GetStationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.OwnerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
FROM bookings
ORDER BY created_at DESC
LIMIT $1
`

type ListBookingsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

func (q *Queries) ListBookings(ctx context.Context, limit int32) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsRow{}
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CollectorID,
			&i.Status,
			&i.Address,
			&i.Longitude,
			&i.Latitude,
			&i.EstimatedKg,
			&i.MaterialType,
			&i.Note,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StationID,
			&i.PinCode,
			&i.PinExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
FROM bookings
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListBookingsByStatusParams struct {
	Status BookingStatus `json:"status"`
	Limit  int32         `json:"limit"`
}

type ListBookingsByStatusRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

func (q *Queries) ListBookingsByStatus(ctx context.Context, arg ListBookingsByStatusParams) ([]ListBookingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByStatusRow{}
	for rows.Next() {
		var i ListBookingsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CollectorID,
			&i.Status,
			&i.Address,
			&i.Longitude,
			&i.Latitude,
			&i.EstimatedKg,
			&i.MaterialType,
			&i.Note,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StationID,
			&i.PinCode,
			&i.PinExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyBookings = `-- name: ListMyBookings :many

SELECT
    id, customer_id, collector_id, status, address,
    ST_X(location)::float8 AS longitude,
    ST_Y(location)::float8 AS latitude,
    estimated_kg, material_type, note, scheduled_at,
    created_at, updated_at, station_id,
    pin_code, pin_expired_at
FROM bookings
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMyBookingsParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	Limit      int32       `json:"limit"`
}

type ListMyBookingsRow struct {
	ID           pgtype.UUID        `json:"id"`
	CustomerID   pgtype.UUID        `json:"customer_id"`
	CollectorID  pgtype.UUID        `json:"collector_id"`
	Status       BookingStatus      `json:"status"`
	Address      string             `json:"address"`
	Longitude    float64            `json:"longitude"`
	Latitude     float64            `json:"latitude"`
	EstimatedKg  pgtype.Numeric     `json:"estimated_kg"`
	MaterialType MaterialType       `json:"material_type"`
	Note         *string            `json:"note"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	StationID    pgtype.UUID        `json:"station_id"`
	PinCode      *string            `json:"pin_code"`
	PinExpiredAt pgtype.Timestamptz `json:"pin_expired_at"`
}

// ─── List queries (refresh RETURNING với cột mới) ─────────────
func (q *Queries) ListMyBookings(ctx context.Context, arg ListMyBookingsParams) ([]ListMyBookingsRow, error) {
	rows, err := q.db.Query(ctx, listMyBookings, arg.CustomerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyBookingsRow{}
	for rows.Next() {
		var i ListMyBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CollectorID,
			&i.Status,
			&i.Address,
			&i.Longitude,
			&i.Latitude,
			&i.EstimatedKg,
			&i.MaterialType,
			&i.Note,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StationID,
			&i.PinCode,
			&i.PinExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollbackBookingAccept = `-- name: RollbackBookingAccept :exec
UPDATE bookings
SET status     = 'pending',
    station_id = NULL,
    updated_at = NOW()
WHERE id = $1 AND status = 'accepted' AND station_id = $2
`

type RollbackBookingAcceptParams struct {
	ID        pgtype.UUID `json:"id"`
	StationID pgtype.UUID `json:"station_id"`
}

// Hoàn về PENDING nếu DeductFee fail (compensation).
func (q *Queries) RollbackBookingAccept(ctx context.Context, arg RollbackBookingAcceptParams) error {
	_, err := q.db.Exec(ctx, rollbackBookingAccept, arg.ID, arg.StationID)
	return err
}

const rollbackDriverComplete = `-- name: RollbackDriverComplete :exec
UPDATE bookings
SET driver_weight    = NULL,
    proof_image_url  = NULL,
    collector_id     = NULL,
    status           = 'accepted',
    updated_at       = NOW()
WHERE id = $1 AND status = 'delivered_to_station'
`

// Hoàn về ACCEPTED nếu IssuePendingReward fail.
func (q *Queries) RollbackDriverComplete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rollbackDriverComplete, id)
	return err
}

const setBookingPendingTxIds = `-- name: SetBookingPendingTxIds :exec
UPDATE bookings
SET user_pending_tx_id   = $2,
    driver_pending_tx_id = $3,
    updated_at           = NOW()
WHERE id = $1
`

type SetBookingPendingTxIdsParams struct {
	ID                pgtype.UUID `json:"id"`
	UserPendingTxID   pgtype.UUID `json:"user_pending_tx_id"`
	DriverPendingTxID pgtype.UUID `json:"driver_pending_tx_id"`
}

// Lưu tx_id của 2 IssuePendingReward để CollectorVerifyBooking dùng sau.
func (q *Queries) SetBookingPendingTxIds(ctx context.Context, arg SetBookingPendingTxIdsParams) error {
	_, err := q.db.Exec(ctx, setBookingPendingTxIds, arg.ID, arg.UserPendingTxID, arg.DriverPendingTxID)
	return err
}
