// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ecopoint/point/v1/point.proto

package pointv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PointService_DeductFee_FullMethodName          = "/ecopoint.point.v1.PointService/DeductFee"
	PointService_IssuePendingReward_FullMethodName = "/ecopoint.point.v1.PointService/IssuePendingReward"
	PointService_ConfirmReward_FullMethodName      = "/ecopoint.point.v1.PointService/ConfirmReward"
	PointService_CancelReward_FullMethodName       = "/ecopoint.point.v1.PointService/CancelReward"
	PointService_GetBalance_FullMethodName         = "/ecopoint.point.v1.PointService/GetBalance"
)

// PointServiceClient is the client API for PointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PointService — V1.3 Two-Phase Ledger.
// 1 EP = 100 VNĐ. Mọi cột tiền dùng int64 (không còn float / Decimal).
type PointServiceClient interface {
	// Trừ thẳng quỹ khả dụng — dùng cho phí 20 EP của Vựa,
	// redeem voucher, phí giao dịch B2B Phase 3.
	DeductFee(ctx context.Context, in *DeductFeeRequest, opts ...grpc.CallOption) (*DeductFeeResponse, error)
	// Driver chốt đơn → cộng điểm vào balance_pending,
	// chưa khả dụng cho user đến khi Vựa Confirm.
	IssuePendingReward(ctx context.Context, in *IssueRewardRequest, opts ...grpc.CallOption) (*IssueRewardResponse, error)
	// Vựa xác nhận nhập kho → pending chuyển sang available.
	ConfirmReward(ctx context.Context, in *ConfirmRewardRequest, opts ...grpc.CallOption) (*ConfirmRewardResponse, error)
	// Vựa phát hiện gian lận / lệch cân > 10% → huỷ pending,
	// trừ điểm khỏi balance_pending mà KHÔNG cộng vào available.
	CancelReward(ctx context.Context, in *CancelRewardRequest, opts ...grpc.CallOption) (*CancelRewardResponse, error)
	// Đọc số dư (cho UI / Gateway).
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type pointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPointServiceClient(cc grpc.ClientConnInterface) PointServiceClient {
	return &pointServiceClient{cc}
}

func (c *pointServiceClient) DeductFee(ctx context.Context, in *DeductFeeRequest, opts ...grpc.CallOption) (*DeductFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductFeeResponse)
	err := c.cc.Invoke(ctx, PointService_DeductFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) IssuePendingReward(ctx context.Context, in *IssueRewardRequest, opts ...grpc.CallOption) (*IssueRewardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueRewardResponse)
	err := c.cc.Invoke(ctx, PointService_IssuePendingReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) ConfirmReward(ctx context.Context, in *ConfirmRewardRequest, opts ...grpc.CallOption) (*ConfirmRewardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmRewardResponse)
	err := c.cc.Invoke(ctx, PointService_ConfirmReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) CancelReward(ctx context.Context, in *CancelRewardRequest, opts ...grpc.CallOption) (*CancelRewardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRewardResponse)
	err := c.cc.Invoke(ctx, PointService_CancelReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pointServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, PointService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PointServiceServer is the server API for PointService service.
// All implementations should embed UnimplementedPointServiceServer
// for forward compatibility.
//
// PointService — V1.3 Two-Phase Ledger.
// 1 EP = 100 VNĐ. Mọi cột tiền dùng int64 (không còn float / Decimal).
type PointServiceServer interface {
	// Trừ thẳng quỹ khả dụng — dùng cho phí 20 EP của Vựa,
	// redeem voucher, phí giao dịch B2B Phase 3.
	DeductFee(context.Context, *DeductFeeRequest) (*DeductFeeResponse, error)
	// Driver chốt đơn → cộng điểm vào balance_pending,
	// chưa khả dụng cho user đến khi Vựa Confirm.
	IssuePendingReward(context.Context, *IssueRewardRequest) (*IssueRewardResponse, error)
	// Vựa xác nhận nhập kho → pending chuyển sang available.
	ConfirmReward(context.Context, *ConfirmRewardRequest) (*ConfirmRewardResponse, error)
	// Vựa phát hiện gian lận / lệch cân > 10% → huỷ pending,
	// trừ điểm khỏi balance_pending mà KHÔNG cộng vào available.
	CancelReward(context.Context, *CancelRewardRequest) (*CancelRewardResponse, error)
	// Đọc số dư (cho UI / Gateway).
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
}

// UnimplementedPointServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPointServiceServer struct{}

func (UnimplementedPointServiceServer) DeductFee(context.Context, *DeductFeeRequest) (*DeductFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeductFee not implemented")
}
func (UnimplementedPointServiceServer) IssuePendingReward(context.Context, *IssueRewardRequest) (*IssueRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePendingReward not implemented")
}
func (UnimplementedPointServiceServer) ConfirmReward(context.Context, *ConfirmRewardRequest) (*ConfirmRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmReward not implemented")
}
func (UnimplementedPointServiceServer) CancelReward(context.Context, *CancelRewardRequest) (*CancelRewardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelReward not implemented")
}
func (UnimplementedPointServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPointServiceServer) testEmbeddedByValue() {}

// UnsafePointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PointServiceServer will
// result in compilation errors.
type UnsafePointServiceServer interface {
	mustEmbedUnimplementedPointServiceServer()
}

func RegisterPointServiceServer(s grpc.ServiceRegistrar, srv PointServiceServer) {
	// If the following call pancis, it indicates UnimplementedPointServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PointService_ServiceDesc, srv)
}

func _PointService_DeductFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).DeductFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_DeductFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).DeductFee(ctx, req.(*DeductFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_IssuePendingReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).IssuePendingReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_IssuePendingReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).IssuePendingReward(ctx, req.(*IssueRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_ConfirmReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).ConfirmReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_ConfirmReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).ConfirmReward(ctx, req.(*ConfirmRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_CancelReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).CancelReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_CancelReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).CancelReward(ctx, req.(*CancelRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PointService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PointServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PointService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PointServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PointService_ServiceDesc is the grpc.ServiceDesc for PointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecopoint.point.v1.PointService",
	HandlerType: (*PointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeductFee",
			Handler:    _PointService_DeductFee_Handler,
		},
		{
			MethodName: "IssuePendingReward",
			Handler:    _PointService_IssuePendingReward_Handler,
		},
		{
			MethodName: "ConfirmReward",
			Handler:    _PointService_ConfirmReward_Handler,
		},
		{
			MethodName: "CancelReward",
			Handler:    _PointService_CancelReward_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PointService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecopoint/point/v1/point.proto",
}
