// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=js"
// @generated from file ecopoint/user/v1/user.proto (package ecopoint.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserInfoRequest, GetUserInfoResponse, VerifyTokenRequest, VerifyTokenResponse } from "./user_pbjs";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.user.v1.UserService
 */
export const UserService = {
  typeName: "ecopoint.user.v1.UserService",
  methods: {
    /**
     * @generated from rpc ecopoint.user.v1.UserService.GetUserInfo
     */
    getUserInfo: {
      name: "GetUserInfo",
      I: GetUserInfoRequest,
      O: GetUserInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.user.v1.UserService.VerifyToken
     */
    verifyToken: {
      name: "VerifyToken",
      I: VerifyTokenRequest,
      O: VerifyTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

