// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=js"
// @generated from file ecopoint/user/v1/user.proto (package ecopoint.user.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ecopoint/user/v1/user.proto.
 */
export const file_ecopoint_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChtlY29wb2ludC91c2VyL3YxL3VzZXIucHJvdG8SEGVjb3BvaW50LnVzZXIudjEi9AEKBFVzZXISCgoCaWQYASABKAkSDQoFcGhvbmUYAiABKAkSDQoFZW1haWwYAyABKAkSEQoJZnVsbF9uYW1lGAQgASgJEhIKCmF2YXRhcl91cmwYBSABKAkSKAoEcm9sZRgGIAEoDjIaLmVjb3BvaW50LnVzZXIudjEuVXNlclJvbGUSEQoJaXNfYWN0aXZlGAcgASgIEi4KCmNyZWF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIiUKEkdldFVzZXJJbmZvUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgJIjsKE0dldFVzZXJJbmZvUmVzcG9uc2USJAoEdXNlchgBIAEoCzIWLmVjb3BvaW50LnVzZXIudjEuVXNlciIqChJWZXJpZnlUb2tlblJlcXVlc3QSFAoMYWNjZXNzX3Rva2VuGAEgASgJIo8BChNWZXJpZnlUb2tlblJlc3BvbnNlEg0KBXZhbGlkGAEgASgIEg8KB3VzZXJfaWQYAiABKAkSKAoEcm9sZRgDIAEoDjIaLmVjb3BvaW50LnVzZXIudjEuVXNlclJvbGUSLgoKZXhwaXJlc19hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqawoIVXNlclJvbGUSGQoVVVNFUl9ST0xFX1VOU1BFQ0lGSUVEEAASFgoSVVNFUl9ST0xFX0NVU1RPTUVSEAESFwoTVVNFUl9ST0xFX0NPTExFQ1RPUhACEhMKD1VTRVJfUk9MRV9BRE1JThADMsUBCgtVc2VyU2VydmljZRJaCgtHZXRVc2VySW5mbxIkLmVjb3BvaW50LnVzZXIudjEuR2V0VXNlckluZm9SZXF1ZXN0GiUuZWNvcG9pbnQudXNlci52MS5HZXRVc2VySW5mb1Jlc3BvbnNlEloKC1ZlcmlmeVRva2VuEiQuZWNvcG9pbnQudXNlci52MS5WZXJpZnlUb2tlblJlcXVlc3QaJS5lY29wb2ludC51c2VyLnYxLlZlcmlmeVRva2VuUmVzcG9uc2VCyAEKFGNvbS5lY29wb2ludC51c2VyLnYxQglVc2VyUHJvdG9QAVpDZ2l0aHViLmNvbS9lY29wb2ludC9lY29wb2ludC9zaGFyZWQvbGlicy9nby9lY29wb2ludC91c2VyL3YxO3VzZXJ2MaICA0VVWKoCEEVjb3BvaW50LlVzZXIuVjHKAhBFY29wb2ludFxVc2VyXFYx4gIcRWNvcG9pbnRcVXNlclxWMVxHUEJNZXRhZGF0YeoCEkVjb3BvaW50OjpVc2VyOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message ecopoint.user.v1.User
 */
export type User = Message<"ecopoint.user.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string phone = 2;
   */
  phone: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string full_name = 4;
   */
  fullName: string;

  /**
   * @generated from field: string avatar_url = 5;
   */
  avatarUrl: string;

  /**
   * @generated from field: ecopoint.user.v1.UserRole role = 6;
   */
  role: UserRole;

  /**
   * @generated from field: bool is_active = 7;
   */
  isActive: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message ecopoint.user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_ecopoint_user_v1_user, 0);

/**
 * @generated from message ecopoint.user.v1.GetUserInfoRequest
 */
export type GetUserInfoRequest = Message<"ecopoint.user.v1.GetUserInfoRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message ecopoint.user.v1.GetUserInfoRequest.
 * Use `create(GetUserInfoRequestSchema)` to create a new message.
 */
export const GetUserInfoRequestSchema: GenMessage<GetUserInfoRequest> = /*@__PURE__*/
  messageDesc(file_ecopoint_user_v1_user, 1);

/**
 * @generated from message ecopoint.user.v1.GetUserInfoResponse
 */
export type GetUserInfoResponse = Message<"ecopoint.user.v1.GetUserInfoResponse"> & {
  /**
   * @generated from field: ecopoint.user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message ecopoint.user.v1.GetUserInfoResponse.
 * Use `create(GetUserInfoResponseSchema)` to create a new message.
 */
export const GetUserInfoResponseSchema: GenMessage<GetUserInfoResponse> = /*@__PURE__*/
  messageDesc(file_ecopoint_user_v1_user, 2);

/**
 * @generated from message ecopoint.user.v1.VerifyTokenRequest
 */
export type VerifyTokenRequest = Message<"ecopoint.user.v1.VerifyTokenRequest"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message ecopoint.user.v1.VerifyTokenRequest.
 * Use `create(VerifyTokenRequestSchema)` to create a new message.
 */
export const VerifyTokenRequestSchema: GenMessage<VerifyTokenRequest> = /*@__PURE__*/
  messageDesc(file_ecopoint_user_v1_user, 3);

/**
 * @generated from message ecopoint.user.v1.VerifyTokenResponse
 */
export type VerifyTokenResponse = Message<"ecopoint.user.v1.VerifyTokenResponse"> & {
  /**
   * @generated from field: bool valid = 1;
   */
  valid: boolean;

  /**
   * @generated from field: string user_id = 2;
   */
  userId: string;

  /**
   * @generated from field: ecopoint.user.v1.UserRole role = 3;
   */
  role: UserRole;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;
};

/**
 * Describes the message ecopoint.user.v1.VerifyTokenResponse.
 * Use `create(VerifyTokenResponseSchema)` to create a new message.
 */
export const VerifyTokenResponseSchema: GenMessage<VerifyTokenResponse> = /*@__PURE__*/
  messageDesc(file_ecopoint_user_v1_user, 4);

/**
 * @generated from enum ecopoint.user.v1.UserRole
 */
export enum UserRole {
  /**
   * @generated from enum value: USER_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Người dân yêu cầu thu gom
   *
   * @generated from enum value: USER_ROLE_CUSTOMER = 1;
   */
  CUSTOMER = 1,

  /**
   * Người thu gom ve chai
   *
   * @generated from enum value: USER_ROLE_COLLECTOR = 2;
   */
  COLLECTOR = 2,

  /**
   * @generated from enum value: USER_ROLE_ADMIN = 3;
   */
  ADMIN = 3,
}

/**
 * Describes the enum ecopoint.user.v1.UserRole.
 */
export const UserRoleSchema: GenEnum<UserRole> = /*@__PURE__*/
  enumDesc(file_ecopoint_user_v1_user, 0);

/**
 * @generated from service ecopoint.user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc ecopoint.user.v1.UserService.GetUserInfo
   */
  getUserInfo: {
    methodKind: "unary";
    input: typeof GetUserInfoRequestSchema;
    output: typeof GetUserInfoResponseSchema;
  },
  /**
   * @generated from rpc ecopoint.user.v1.UserService.VerifyToken
   */
  verifyToken: {
    methodKind: "unary";
    input: typeof VerifyTokenRequestSchema;
    output: typeof VerifyTokenResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ecopoint_user_v1_user, 0);

