// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/user/v1/user.proto (package ecopoint.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthResponse, DeductTrustScoreRequest, DeductTrustScoreResponse, GetUserInfoRequest, GetUserInfoResponse, LoginRequest, RegisterRequest, ValidateTokenRequest, ValidateTokenResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.user.v1.UserService
 */
export const UserService = {
  typeName: "ecopoint.user.v1.UserService",
  methods: {
    /**
     * ----- Auth -----
     *
     * @generated from rpc ecopoint.user.v1.UserService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.user.v1.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.user.v1.UserService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: ValidateTokenRequest,
      O: ValidateTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ----- Profile -----
     *
     * @generated from rpc ecopoint.user.v1.UserService.GetUserInfo
     */
    getUserInfo: {
      name: "GetUserInfo",
      I: GetUserInfoRequest,
      O: GetUserInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ----- Trust Layer (V1.3 Anti-Fraud) -----
     * Trừ trust_score, floor 0. Idempotency do caller tự đảm bảo
     * (vd: chỉ gọi 1 lần khi booking chuyển sang CANCELLED).
     *
     * @generated from rpc ecopoint.user.v1.UserService.DeductTrustScore
     */
    deductTrustScore: {
      name: "DeductTrustScore",
      I: DeductTrustScoreRequest,
      O: DeductTrustScoreResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

