// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/rating/v1/rating.proto (package ecopoint.rating.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SubmitReviewRequest, SubmitReviewResponse } from "./rating_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.rating.v1.RatingService
 */
export const RatingService = {
  typeName: "ecopoint.rating.v1.RatingService",
  methods: {
    /**
     * @generated from rpc ecopoint.rating.v1.RatingService.SubmitReview
     */
    submitReview: {
      name: "SubmitReview",
      I: SubmitReviewRequest,
      O: SubmitReviewResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

