// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/rating/v1/rating.proto (package ecopoint.rating.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ecopoint.rating.v1.Review
 */
export class Review extends Message<Review> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string booking_id = 2;
   */
  bookingId = "";

  /**
   * @generated from field: string user_id = 3;
   */
  userId = "";

  /**
   * @generated from field: string collector_id = 4;
   */
  collectorId = "";

  /**
   * 1..5
   *
   * @generated from field: int32 rating = 5;
   */
  rating = 0;

  /**
   * @generated from field: string comment = 6;
   */
  comment = "";

  /**
   * link đã upload xong qua media-service
   *
   * @generated from field: repeated string media_urls = 7;
   */
  mediaUrls: string[] = [];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<Review>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.rating.v1.Review";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "booking_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "collector_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "rating", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 6, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "media_urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 8, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Review {
    return new Review().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Review {
    return new Review().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Review {
    return new Review().fromJsonString(jsonString, options);
  }

  static equals(a: Review | PlainMessage<Review> | undefined, b: Review | PlainMessage<Review> | undefined): boolean {
    return proto3.util.equals(Review, a, b);
  }
}

/**
 * @generated from message ecopoint.rating.v1.SubmitReviewRequest
 */
export class SubmitReviewRequest extends Message<SubmitReviewRequest> {
  /**
   * @generated from field: string booking_id = 1;
   */
  bookingId = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * @generated from field: string collector_id = 3;
   */
  collectorId = "";

  /**
   * @generated from field: int32 rating = 4;
   */
  rating = 0;

  /**
   * @generated from field: string comment = 5;
   */
  comment = "";

  /**
   * @generated from field: repeated string media_urls = 6;
   */
  mediaUrls: string[] = [];

  constructor(data?: PartialMessage<SubmitReviewRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.rating.v1.SubmitReviewRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "collector_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "rating", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "media_urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitReviewRequest {
    return new SubmitReviewRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitReviewRequest {
    return new SubmitReviewRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitReviewRequest {
    return new SubmitReviewRequest().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitReviewRequest | PlainMessage<SubmitReviewRequest> | undefined, b: SubmitReviewRequest | PlainMessage<SubmitReviewRequest> | undefined): boolean {
    return proto3.util.equals(SubmitReviewRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.rating.v1.SubmitReviewResponse
 */
export class SubmitReviewResponse extends Message<SubmitReviewResponse> {
  /**
   * @generated from field: ecopoint.rating.v1.Review review = 1;
   */
  review?: Review;

  constructor(data?: PartialMessage<SubmitReviewResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.rating.v1.SubmitReviewResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "review", kind: "message", T: Review },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubmitReviewResponse {
    return new SubmitReviewResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubmitReviewResponse {
    return new SubmitReviewResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubmitReviewResponse {
    return new SubmitReviewResponse().fromJsonString(jsonString, options);
  }

  static equals(a: SubmitReviewResponse | PlainMessage<SubmitReviewResponse> | undefined, b: SubmitReviewResponse | PlainMessage<SubmitReviewResponse> | undefined): boolean {
    return proto3.util.equals(SubmitReviewResponse, a, b);
  }
}

