// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pointdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PointTxType string

const (
	PointTxTypeAdd    PointTxType = "add"
	PointTxTypeDeduct PointTxType = "deduct"
)

func (e *PointTxType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PointTxType(s)
	case string:
		*e = PointTxType(s)
	default:
		return fmt.Errorf("unsupported scan type for PointTxType: %T", src)
	}
	return nil
}

type NullPointTxType struct {
	PointTxType PointTxType `json:"point_tx_type"`
	Valid       bool        `json:"valid"` // Valid is true if PointTxType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPointTxType) Scan(value interface{}) error {
	if value == nil {
		ns.PointTxType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PointTxType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPointTxType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PointTxType), nil
}

type PointTransaction struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TxType         PointTxType        `json:"tx_type"`
	Amount         pgtype.Numeric     `json:"amount"`
	BalanceAfter   pgtype.Numeric     `json:"balance_after"`
	Source         *string            `json:"source"`
	ReferenceID    *string            `json:"reference_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Balance   pgtype.Numeric     `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
