// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package pointdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTxByIdempotencyKey = `-- name: GetTxByIdempotencyKey :one
SELECT id, user_id, tx_type, amount, balance_after, source, reference_id, idempotency_key, created_at
FROM point_transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetTxByIdempotencyKey(ctx context.Context, idempotencyKey string) (PointTransaction, error) {
	row := q.db.QueryRow(ctx, getTxByIdempotencyKey, idempotencyKey)
	var i PointTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Source,
		&i.ReferenceID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const insertPointTransaction = `-- name: InsertPointTransaction :one
INSERT INTO point_transactions (
    user_id, tx_type, amount, balance_after,
    source, reference_id, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, tx_type, amount, balance_after, source, reference_id, idempotency_key, created_at
`

type InsertPointTransactionParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	TxType         PointTxType    `json:"tx_type"`
	Amount         pgtype.Numeric `json:"amount"`
	BalanceAfter   pgtype.Numeric `json:"balance_after"`
	Source         *string        `json:"source"`
	ReferenceID    *string        `json:"reference_id"`
	IdempotencyKey string         `json:"idempotency_key"`
}

func (q *Queries) InsertPointTransaction(ctx context.Context, arg InsertPointTransactionParams) (PointTransaction, error) {
	row := q.db.QueryRow(ctx, insertPointTransaction,
		arg.UserID,
		arg.TxType,
		arg.Amount,
		arg.BalanceAfter,
		arg.Source,
		arg.ReferenceID,
		arg.IdempotencyKey,
	)
	var i PointTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TxType,
		&i.Amount,
		&i.BalanceAfter,
		&i.Source,
		&i.ReferenceID,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const lockWallet = `-- name: LockWallet :one
SELECT user_id, balance, created_at, updated_at
FROM wallets
WHERE user_id = $1
FOR UPDATE
`

// Khóa hàng wallet để cập nhật số dư an toàn dưới transaction.
func (q *Queries) LockWallet(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, lockWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE wallets
SET balance    = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, balance, created_at, updated_at
`

type UpdateBalanceParams struct {
	UserID  pgtype.UUID    `json:"user_id"`
	Balance pgtype.Numeric `json:"balance"`
}

// Cập nhật số dư mới sau khi đã tính toán.
func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateBalance, arg.UserID, arg.Balance)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWallet = `-- name: UpsertWallet :one
INSERT INTO wallets (user_id, balance)
VALUES ($1, 0)
ON CONFLICT (user_id) DO UPDATE
    SET user_id = wallets.user_id
RETURNING user_id, balance, created_at, updated_at
`

// Tạo wallet nếu chưa có (idempotent).
func (q *Queries) UpsertWallet(ctx context.Context, userID pgtype.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, upsertWallet, userID)
	var i Wallet
	err := row.Scan(
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
