// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/point/v1/point.proto (package ecopoint.point.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ecopoint.point.v1.PointTransaction
 */
export class PointTransaction extends Message<PointTransaction> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * "add" | "deduct"
   *
   * @generated from field: string tx_type = 3;
   */
  txType = "";

  /**
   * luôn dương
   *
   * @generated from field: int64 amount = 4;
   */
  amount = protoInt64.zero;

  /**
   * tổng = available + pending sau tx commit
   *
   * @generated from field: int64 balance_after = 5;
   */
  balanceAfter = protoInt64.zero;

  /**
   * "pending" | "available" | "cancelled"
   *
   * @generated from field: string status = 6;
   */
  status = "";

  /**
   * @generated from field: string source = 7;
   */
  source = "";

  /**
   * @generated from field: string reference_id = 8;
   */
  referenceId = "";

  /**
   * @generated from field: string idempotency_key = 9;
   */
  idempotencyKey = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 10;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<PointTransaction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.PointTransaction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "tx_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "balance_after", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 6, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PointTransaction {
    return new PointTransaction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PointTransaction {
    return new PointTransaction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PointTransaction {
    return new PointTransaction().fromJsonString(jsonString, options);
  }

  static equals(a: PointTransaction | PlainMessage<PointTransaction> | undefined, b: PointTransaction | PlainMessage<PointTransaction> | undefined): boolean {
    return proto3.util.equals(PointTransaction, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.GetBalanceRequest
 */
export class GetBalanceRequest extends Message<GetBalanceRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<GetBalanceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.GetBalanceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined, b: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined): boolean {
    return proto3.util.equals(GetBalanceRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.GetBalanceResponse
 */
export class GetBalanceResponse extends Message<GetBalanceResponse> {
  /**
   * @generated from field: int64 balance_available = 1;
   */
  balanceAvailable = protoInt64.zero;

  /**
   * @generated from field: int64 balance_pending = 2;
   */
  balancePending = protoInt64.zero;

  constructor(data?: PartialMessage<GetBalanceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.GetBalanceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "balance_available", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "balance_pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined, b: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined): boolean {
    return proto3.util.equals(GetBalanceResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.DeductFeeRequest
 */
export class DeductFeeRequest extends Message<DeductFeeRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * "station_fee_20ep" | "redeem_voucher" | "platform_fee" | ...
   *
   * @generated from field: string reason = 3;
   */
  reason = "";

  /**
   * booking_id / voucher_id / ...
   *
   * @generated from field: string reference_id = 4;
   */
  referenceId = "";

  /**
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<DeductFeeRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.DeductFeeRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeductFeeRequest {
    return new DeductFeeRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeductFeeRequest {
    return new DeductFeeRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeductFeeRequest {
    return new DeductFeeRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeductFeeRequest | PlainMessage<DeductFeeRequest> | undefined, b: DeductFeeRequest | PlainMessage<DeductFeeRequest> | undefined): boolean {
    return proto3.util.equals(DeductFeeRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.DeductFeeResponse
 */
export class DeductFeeResponse extends Message<DeductFeeResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: int64 new_balance_available = 2;
   */
  newBalanceAvailable = protoInt64.zero;

  constructor(data?: PartialMessage<DeductFeeResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.DeductFeeResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance_available", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeductFeeResponse {
    return new DeductFeeResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeductFeeResponse {
    return new DeductFeeResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeductFeeResponse {
    return new DeductFeeResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeductFeeResponse | PlainMessage<DeductFeeResponse> | undefined, b: DeductFeeResponse | PlainMessage<DeductFeeResponse> | undefined): boolean {
    return proto3.util.equals(DeductFeeResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.IssueRewardRequest
 */
export class IssueRewardRequest extends Message<IssueRewardRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: int64 amount = 2;
   */
  amount = protoInt64.zero;

  /**
   * "booking_reward" | "promotion" | ...
   *
   * @generated from field: string source = 3;
   */
  source = "";

  /**
   * @generated from field: string reference_id = 4;
   */
  referenceId = "";

  /**
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<IssueRewardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.IssueRewardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IssueRewardRequest {
    return new IssueRewardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IssueRewardRequest {
    return new IssueRewardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IssueRewardRequest {
    return new IssueRewardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: IssueRewardRequest | PlainMessage<IssueRewardRequest> | undefined, b: IssueRewardRequest | PlainMessage<IssueRewardRequest> | undefined): boolean {
    return proto3.util.equals(IssueRewardRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.IssueRewardResponse
 */
export class IssueRewardResponse extends Message<IssueRewardResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: int64 new_balance_pending = 2;
   */
  newBalancePending = protoInt64.zero;

  constructor(data?: PartialMessage<IssueRewardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.IssueRewardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance_pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IssueRewardResponse {
    return new IssueRewardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IssueRewardResponse {
    return new IssueRewardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IssueRewardResponse {
    return new IssueRewardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: IssueRewardResponse | PlainMessage<IssueRewardResponse> | undefined, b: IssueRewardResponse | PlainMessage<IssueRewardResponse> | undefined): boolean {
    return proto3.util.equals(IssueRewardResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.ConfirmRewardRequest
 */
export class ConfirmRewardRequest extends Message<ConfirmRewardRequest> {
  /**
   * @generated from field: string transaction_id = 1;
   */
  transactionId = "";

  /**
   * station_id (logical, không FK chéo DB)
   *
   * @generated from field: string confirmed_by = 2;
   */
  confirmedBy = "";

  constructor(data?: PartialMessage<ConfirmRewardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.ConfirmRewardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "confirmed_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConfirmRewardRequest {
    return new ConfirmRewardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConfirmRewardRequest {
    return new ConfirmRewardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConfirmRewardRequest {
    return new ConfirmRewardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ConfirmRewardRequest | PlainMessage<ConfirmRewardRequest> | undefined, b: ConfirmRewardRequest | PlainMessage<ConfirmRewardRequest> | undefined): boolean {
    return proto3.util.equals(ConfirmRewardRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.ConfirmRewardResponse
 */
export class ConfirmRewardResponse extends Message<ConfirmRewardResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: int64 new_balance_available = 2;
   */
  newBalanceAvailable = protoInt64.zero;

  /**
   * @generated from field: int64 new_balance_pending = 3;
   */
  newBalancePending = protoInt64.zero;

  constructor(data?: PartialMessage<ConfirmRewardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.ConfirmRewardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance_available", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "new_balance_pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConfirmRewardResponse {
    return new ConfirmRewardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConfirmRewardResponse {
    return new ConfirmRewardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConfirmRewardResponse {
    return new ConfirmRewardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ConfirmRewardResponse | PlainMessage<ConfirmRewardResponse> | undefined, b: ConfirmRewardResponse | PlainMessage<ConfirmRewardResponse> | undefined): boolean {
    return proto3.util.equals(ConfirmRewardResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.CancelRewardRequest
 */
export class CancelRewardRequest extends Message<CancelRewardRequest> {
  /**
   * @generated from field: string transaction_id = 1;
   */
  transactionId = "";

  /**
   * "weight_mismatch" | "fraud_detected" | ...
   *
   * @generated from field: string reason = 2;
   */
  reason = "";

  constructor(data?: PartialMessage<CancelRewardRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.CancelRewardRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelRewardRequest {
    return new CancelRewardRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelRewardRequest {
    return new CancelRewardRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelRewardRequest {
    return new CancelRewardRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CancelRewardRequest | PlainMessage<CancelRewardRequest> | undefined, b: CancelRewardRequest | PlainMessage<CancelRewardRequest> | undefined): boolean {
    return proto3.util.equals(CancelRewardRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.CancelRewardResponse
 */
export class CancelRewardResponse extends Message<CancelRewardResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: int64 new_balance_pending = 2;
   */
  newBalancePending = protoInt64.zero;

  constructor(data?: PartialMessage<CancelRewardResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.CancelRewardResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance_pending", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CancelRewardResponse {
    return new CancelRewardResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CancelRewardResponse {
    return new CancelRewardResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CancelRewardResponse {
    return new CancelRewardResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CancelRewardResponse | PlainMessage<CancelRewardResponse> | undefined, b: CancelRewardResponse | PlainMessage<CancelRewardResponse> | undefined): boolean {
    return proto3.util.equals(CancelRewardResponse, a, b);
  }
}

