// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/point/v1/point.proto (package ecopoint.point.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddPointsRequest, AddPointsResponse, DeductPointsRequest, DeductPointsResponse } from "./point_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.point.v1.PointService
 */
export const PointService = {
  typeName: "ecopoint.point.v1.PointService",
  methods: {
    /**
     * @generated from rpc ecopoint.point.v1.PointService.AddPoints
     */
    addPoints: {
      name: "AddPoints",
      I: AddPointsRequest,
      O: AddPointsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.point.v1.PointService.DeductPoints
     */
    deductPoints: {
      name: "DeductPoints",
      I: DeductPointsRequest,
      O: DeductPointsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

