// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/point/v1/point.proto (package ecopoint.point.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Decimal } from "../../common/v1/common_pb.js";

/**
 * @generated from enum ecopoint.point.v1.PointSource
 */
export enum PointSource {
  /**
   * @generated from enum value: POINT_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Hoàn thành đơn thu gom
   *
   * @generated from enum value: POINT_SOURCE_BOOKING = 1;
   */
  BOOKING = 1,

  /**
   * Khuyến mãi / quà tặng
   *
   * @generated from enum value: POINT_SOURCE_PROMOTION = 2;
   */
  PROMOTION = 2,

  /**
   * Hoàn điểm
   *
   * @generated from enum value: POINT_SOURCE_REFUND = 3;
   */
  REFUND = 3,

  /**
   * Điều chỉnh từ admin
   *
   * @generated from enum value: POINT_SOURCE_ADJUSTMENT = 4;
   */
  ADJUSTMENT = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PointSource)
proto3.util.setEnumType(PointSource, "ecopoint.point.v1.PointSource", [
  { no: 0, name: "POINT_SOURCE_UNSPECIFIED" },
  { no: 1, name: "POINT_SOURCE_BOOKING" },
  { no: 2, name: "POINT_SOURCE_PROMOTION" },
  { no: 3, name: "POINT_SOURCE_REFUND" },
  { no: 4, name: "POINT_SOURCE_ADJUSTMENT" },
]);

/**
 * @generated from enum ecopoint.point.v1.PointDeductReason
 */
export enum PointDeductReason {
  /**
   * @generated from enum value: POINT_DEDUCT_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Đổi phần thưởng
   *
   * @generated from enum value: POINT_DEDUCT_REASON_REDEEM = 1;
   */
  REDEEM = 1,

  /**
   * @generated from enum value: POINT_DEDUCT_REASON_EXPIRED = 2;
   */
  EXPIRED = 2,

  /**
   * @generated from enum value: POINT_DEDUCT_REASON_PENALTY = 3;
   */
  PENALTY = 3,

  /**
   * @generated from enum value: POINT_DEDUCT_REASON_ADJUSTMENT = 4;
   */
  ADJUSTMENT = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(PointDeductReason)
proto3.util.setEnumType(PointDeductReason, "ecopoint.point.v1.PointDeductReason", [
  { no: 0, name: "POINT_DEDUCT_REASON_UNSPECIFIED" },
  { no: 1, name: "POINT_DEDUCT_REASON_REDEEM" },
  { no: 2, name: "POINT_DEDUCT_REASON_EXPIRED" },
  { no: 3, name: "POINT_DEDUCT_REASON_PENALTY" },
  { no: 4, name: "POINT_DEDUCT_REASON_ADJUSTMENT" },
]);

/**
 * @generated from message ecopoint.point.v1.GetBalanceRequest
 */
export class GetBalanceRequest extends Message<GetBalanceRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  constructor(data?: PartialMessage<GetBalanceRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.GetBalanceRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceRequest {
    return new GetBalanceRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined, b: GetBalanceRequest | PlainMessage<GetBalanceRequest> | undefined): boolean {
    return proto3.util.equals(GetBalanceRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.GetBalanceResponse
 */
export class GetBalanceResponse extends Message<GetBalanceResponse> {
  /**
   * @generated from field: ecopoint.common.v1.Decimal balance = 1;
   */
  balance?: Decimal;

  constructor(data?: PartialMessage<GetBalanceResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.GetBalanceResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "balance", kind: "message", T: Decimal },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetBalanceResponse {
    return new GetBalanceResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined, b: GetBalanceResponse | PlainMessage<GetBalanceResponse> | undefined): boolean {
    return proto3.util.equals(GetBalanceResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.PointTransaction
 */
export class PointTransaction extends Message<PointTransaction> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string user_id = 2;
   */
  userId = "";

  /**
   * luôn dương
   *
   * @generated from field: ecopoint.common.v1.Decimal amount = 3;
   */
  amount?: Decimal;

  /**
   * @generated from field: ecopoint.common.v1.Decimal balance_after = 4;
   */
  balanceAfter?: Decimal;

  /**
   * booking_id / reward_id
   *
   * @generated from field: string reference_id = 5;
   */
  referenceId = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<PointTransaction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.PointTransaction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "amount", kind: "message", T: Decimal },
    { no: 4, name: "balance_after", kind: "message", T: Decimal },
    { no: 5, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "created_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PointTransaction {
    return new PointTransaction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PointTransaction {
    return new PointTransaction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PointTransaction {
    return new PointTransaction().fromJsonString(jsonString, options);
  }

  static equals(a: PointTransaction | PlainMessage<PointTransaction> | undefined, b: PointTransaction | PlainMessage<PointTransaction> | undefined): boolean {
    return proto3.util.equals(PointTransaction, a, b);
  }
}

/**
 * ---- AddPoints ----
 *
 * @generated from message ecopoint.point.v1.AddPointsRequest
 */
export class AddPointsRequest extends Message<AddPointsRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: ecopoint.common.v1.Decimal amount = 2;
   */
  amount?: Decimal;

  /**
   * @generated from field: ecopoint.point.v1.PointSource source = 3;
   */
  source = PointSource.UNSPECIFIED;

  /**
   * @generated from field: string reference_id = 4;
   */
  referenceId = "";

  /**
   * Idempotency key để chống cộng điểm trùng khi retry.
   *
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<AddPointsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.AddPointsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "message", T: Decimal },
    { no: 3, name: "source", kind: "enum", T: proto3.getEnumType(PointSource) },
    { no: 4, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddPointsRequest {
    return new AddPointsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddPointsRequest {
    return new AddPointsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddPointsRequest {
    return new AddPointsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: AddPointsRequest | PlainMessage<AddPointsRequest> | undefined, b: AddPointsRequest | PlainMessage<AddPointsRequest> | undefined): boolean {
    return proto3.util.equals(AddPointsRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.AddPointsResponse
 */
export class AddPointsResponse extends Message<AddPointsResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: ecopoint.common.v1.Decimal new_balance = 2;
   */
  newBalance?: Decimal;

  constructor(data?: PartialMessage<AddPointsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.AddPointsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance", kind: "message", T: Decimal },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddPointsResponse {
    return new AddPointsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddPointsResponse {
    return new AddPointsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddPointsResponse {
    return new AddPointsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: AddPointsResponse | PlainMessage<AddPointsResponse> | undefined, b: AddPointsResponse | PlainMessage<AddPointsResponse> | undefined): boolean {
    return proto3.util.equals(AddPointsResponse, a, b);
  }
}

/**
 * ---- DeductPoints ----
 *
 * @generated from message ecopoint.point.v1.DeductPointsRequest
 */
export class DeductPointsRequest extends Message<DeductPointsRequest> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId = "";

  /**
   * @generated from field: ecopoint.common.v1.Decimal amount = 2;
   */
  amount?: Decimal;

  /**
   * @generated from field: ecopoint.point.v1.PointDeductReason reason = 3;
   */
  reason = PointDeductReason.UNSPECIFIED;

  /**
   * @generated from field: string reference_id = 4;
   */
  referenceId = "";

  /**
   * @generated from field: string idempotency_key = 5;
   */
  idempotencyKey = "";

  constructor(data?: PartialMessage<DeductPointsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.DeductPointsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "amount", kind: "message", T: Decimal },
    { no: 3, name: "reason", kind: "enum", T: proto3.getEnumType(PointDeductReason) },
    { no: 4, name: "reference_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "idempotency_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeductPointsRequest {
    return new DeductPointsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeductPointsRequest {
    return new DeductPointsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeductPointsRequest {
    return new DeductPointsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeductPointsRequest | PlainMessage<DeductPointsRequest> | undefined, b: DeductPointsRequest | PlainMessage<DeductPointsRequest> | undefined): boolean {
    return proto3.util.equals(DeductPointsRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.point.v1.DeductPointsResponse
 */
export class DeductPointsResponse extends Message<DeductPointsResponse> {
  /**
   * @generated from field: ecopoint.point.v1.PointTransaction transaction = 1;
   */
  transaction?: PointTransaction;

  /**
   * @generated from field: ecopoint.common.v1.Decimal new_balance = 2;
   */
  newBalance?: Decimal;

  constructor(data?: PartialMessage<DeductPointsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.point.v1.DeductPointsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "transaction", kind: "message", T: PointTransaction },
    { no: 2, name: "new_balance", kind: "message", T: Decimal },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeductPointsResponse {
    return new DeductPointsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeductPointsResponse {
    return new DeductPointsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeductPointsResponse {
    return new DeductPointsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeductPointsResponse | PlainMessage<DeductPointsResponse> | undefined, b: DeductPointsResponse | PlainMessage<DeductPointsResponse> | undefined): boolean {
    return proto3.util.equals(DeductPointsResponse, a, b);
  }
}

