// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/point/v1/point.proto (package ecopoint.point.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelRewardRequest, CancelRewardResponse, ConfirmRewardRequest, ConfirmRewardResponse, DeductFeeRequest, DeductFeeResponse, GetBalanceRequest, GetBalanceResponse, IssueRewardRequest, IssueRewardResponse } from "./point_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PointService — V1.3 Two-Phase Ledger.
 * 1 EP = 100 VNĐ. Mọi cột tiền dùng int64 (không còn float / Decimal).
 *
 * @generated from service ecopoint.point.v1.PointService
 */
export const PointService = {
  typeName: "ecopoint.point.v1.PointService",
  methods: {
    /**
     * Trừ thẳng quỹ khả dụng — dùng cho phí 20 EP của Vựa,
     * redeem voucher, phí giao dịch B2B Phase 3.
     *
     * @generated from rpc ecopoint.point.v1.PointService.DeductFee
     */
    deductFee: {
      name: "DeductFee",
      I: DeductFeeRequest,
      O: DeductFeeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Driver chốt đơn → cộng điểm vào balance_pending,
     * chưa khả dụng cho user đến khi Vựa Confirm.
     *
     * @generated from rpc ecopoint.point.v1.PointService.IssuePendingReward
     */
    issuePendingReward: {
      name: "IssuePendingReward",
      I: IssueRewardRequest,
      O: IssueRewardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Vựa xác nhận nhập kho → pending chuyển sang available.
     *
     * @generated from rpc ecopoint.point.v1.PointService.ConfirmReward
     */
    confirmReward: {
      name: "ConfirmReward",
      I: ConfirmRewardRequest,
      O: ConfirmRewardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Vựa phát hiện gian lận / lệch cân > 10% → huỷ pending,
     * trừ điểm khỏi balance_pending mà KHÔNG cộng vào available.
     *
     * @generated from rpc ecopoint.point.v1.PointService.CancelReward
     */
    cancelReward: {
      name: "CancelReward",
      I: CancelRewardRequest,
      O: CancelRewardResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Đọc số dư (cho UI / Gateway).
     *
     * @generated from rpc ecopoint.point.v1.PointService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: GetBalanceRequest,
      O: GetBalanceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

