// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/media/v1/media.proto (package ecopoint.media.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message ecopoint.media.v1.GeneratePresignedUrlRequest
 */
export class GeneratePresignedUrlRequest extends Message<GeneratePresignedUrlRequest> {
  /**
   * Tên file gốc do app cung cấp (sẽ được sanitize).
   *
   * @generated from field: string filename = 1;
   */
  filename = "";

  /**
   * MIME type, ví dụ "image/jpeg". Optional, server không bắt buộc client gửi.
   *
   * @generated from field: string content_type = 2;
   */
  contentType = "";

  /**
   * Bucket đích. Bỏ trống = dùng default bucket của media-service.
   *
   * @generated from field: string bucket = 3;
   */
  bucket = "";

  constructor(data?: PartialMessage<GeneratePresignedUrlRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.media.v1.GeneratePresignedUrlRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "content_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "bucket", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneratePresignedUrlRequest {
    return new GeneratePresignedUrlRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneratePresignedUrlRequest {
    return new GeneratePresignedUrlRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneratePresignedUrlRequest {
    return new GeneratePresignedUrlRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GeneratePresignedUrlRequest | PlainMessage<GeneratePresignedUrlRequest> | undefined, b: GeneratePresignedUrlRequest | PlainMessage<GeneratePresignedUrlRequest> | undefined): boolean {
    return proto3.util.equals(GeneratePresignedUrlRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.media.v1.GeneratePresignedUrlResponse
 */
export class GeneratePresignedUrlResponse extends Message<GeneratePresignedUrlResponse> {
  /**
   * URL để mobile app gọi PUT kèm body file.
   *
   * @generated from field: string upload_url = 1;
   */
  uploadUrl = "";

  /**
   * Key (path) của object trong bucket — backend lưu cùng entity (booking, review…).
   *
   * @generated from field: string object_key = 2;
   */
  objectKey = "";

  /**
   * URL công khai để download/render sau khi upload xong.
   *
   * @generated from field: string public_url = 3;
   */
  publicUrl = "";

  /**
   * Thời điểm hết hạn của upload_url.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<GeneratePresignedUrlResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.media.v1.GeneratePresignedUrlResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "upload_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "object_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "public_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "expires_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneratePresignedUrlResponse {
    return new GeneratePresignedUrlResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneratePresignedUrlResponse {
    return new GeneratePresignedUrlResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneratePresignedUrlResponse {
    return new GeneratePresignedUrlResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GeneratePresignedUrlResponse | PlainMessage<GeneratePresignedUrlResponse> | undefined, b: GeneratePresignedUrlResponse | PlainMessage<GeneratePresignedUrlResponse> | undefined): boolean {
    return proto3.util.equals(GeneratePresignedUrlResponse, a, b);
  }
}

