// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/media/v1/media.proto (package ecopoint.media.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GeneratePresignedUrlRequest, GeneratePresignedUrlResponse } from "./media_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.media.v1.MediaService
 */
export const MediaService = {
  typeName: "ecopoint.media.v1.MediaService",
  methods: {
    /**
     * Tạo URL pre-signed để mobile app PUT trực tiếp lên MinIO/S3,
     * tránh upload đi qua backend. Hết hạn sau 15 phút.
     *
     * @generated from rpc ecopoint.media.v1.MediaService.GeneratePresignedUrl
     */
    generatePresignedUrl: {
      name: "GeneratePresignedUrl",
      I: GeneratePresignedUrlRequest,
      O: GeneratePresignedUrlResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

