// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,import_extension=js"
// @generated from file ecopoint/common/v1/common.proto (package ecopoint.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ecopoint/common/v1/common.proto.
 */
export const file_ecopoint_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("Ch9lY29wb2ludC9jb21tb24vdjEvY29tbW9uLnByb3RvEhJlY29wb2ludC5jb21tb24udjEiGAoHRGVjaW1hbBINCgV2YWx1ZRgBIAEoCSIyCg5NdXRhdGlvblJlc3VsdBIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAlC2AEKFmNvbS5lY29wb2ludC5jb21tb24udjFCC0NvbW1vblByb3RvUAFaR2dpdGh1Yi5jb20vZWNvcG9pbnQvZWNvcG9pbnQvc2hhcmVkL2xpYnMvZ28vZWNvcG9pbnQvY29tbW9uL3YxO2NvbW1vbnYxogIDRUNYqgISRWNvcG9pbnQuQ29tbW9uLlYxygISRWNvcG9pbnRcQ29tbW9uXFYx4gIeRWNvcG9pbnRcQ29tbW9uXFYxXEdQQk1ldGFkYXRh6gIURWNvcG9pbnQ6OkNvbW1vbjo6VjFiBnByb3RvMw");

/**
 * Decimal: kiểu số chính xác cho dữ liệu tài chính / điểm thưởng.
 * Dùng chuỗi để tránh mất chính xác như float/double.
 * Format: "123.45" (tối đa 18 chữ số nguyên + 9 chữ số thập phân).
 * Map sang shopspring/decimal (Go) hoặc decimal.js (TS).
 *
 * @generated from message ecopoint.common.v1.Decimal
 */
export type Decimal = Message<"ecopoint.common.v1.Decimal"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;
};

/**
 * Describes the message ecopoint.common.v1.Decimal.
 * Use `create(DecimalSchema)` to create a new message.
 */
export const DecimalSchema: GenMessage<Decimal> = /*@__PURE__*/
  messageDesc(file_ecopoint_common_v1_common, 0);

/**
 * Trạng thái chung trả về từ các mutation.
 *
 * @generated from message ecopoint.common.v1.MutationResult
 */
export type MutationResult = Message<"ecopoint.common.v1.MutationResult"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message ecopoint.common.v1.MutationResult.
 * Use `create(MutationResultSchema)` to create a new message.
 */
export const MutationResultSchema: GenMessage<MutationResult> = /*@__PURE__*/
  messageDesc(file_ecopoint_common_v1_common, 1);

