// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/common/v1/common.proto (package ecopoint.common.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Decimal: kiểu số chính xác cho dữ liệu tài chính / điểm thưởng.
 * Dùng chuỗi để tránh mất chính xác như float/double.
 * Format: "123.45" (tối đa 18 chữ số nguyên + 9 chữ số thập phân).
 * Map sang shopspring/decimal (Go) hoặc decimal.js (TS).
 *
 * @generated from message ecopoint.common.v1.Decimal
 */
export class Decimal extends Message<Decimal> {
  /**
   * @generated from field: string value = 1;
   */
  value = "";

  constructor(data?: PartialMessage<Decimal>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.common.v1.Decimal";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Decimal {
    return new Decimal().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Decimal {
    return new Decimal().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Decimal {
    return new Decimal().fromJsonString(jsonString, options);
  }

  static equals(a: Decimal | PlainMessage<Decimal> | undefined, b: Decimal | PlainMessage<Decimal> | undefined): boolean {
    return proto3.util.equals(Decimal, a, b);
  }
}

/**
 * Trạng thái chung trả về từ các mutation.
 *
 * @generated from message ecopoint.common.v1.MutationResult
 */
export class MutationResult extends Message<MutationResult> {
  /**
   * @generated from field: bool success = 1;
   */
  success = false;

  /**
   * @generated from field: string message = 2;
   */
  message = "";

  constructor(data?: PartialMessage<MutationResult>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.common.v1.MutationResult";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MutationResult {
    return new MutationResult().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MutationResult {
    return new MutationResult().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MutationResult {
    return new MutationResult().fromJsonString(jsonString, options);
  }

  static equals(a: MutationResult | PlainMessage<MutationResult> | undefined, b: MutationResult | PlainMessage<MutationResult> | undefined): boolean {
    return proto3.util.equals(MutationResult, a, b);
  }
}

