// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package rewarddb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RedemptionStatus string

const (
	RedemptionStatusPending   RedemptionStatus = "pending"
	RedemptionStatusCompleted RedemptionStatus = "completed"
	RedemptionStatusCancelled RedemptionStatus = "cancelled"
)

func (e *RedemptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RedemptionStatus(s)
	case string:
		*e = RedemptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RedemptionStatus: %T", src)
	}
	return nil
}

type NullRedemptionStatus struct {
	RedemptionStatus RedemptionStatus `json:"redemption_status"`
	Valid            bool             `json:"valid"` // Valid is true if RedemptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRedemptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RedemptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RedemptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRedemptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RedemptionStatus), nil
}

type Redemption struct {
	ID             pgtype.UUID        `json:"id"`
	VoucherID      pgtype.UUID        `json:"voucher_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	PointCost      pgtype.Numeric     `json:"point_cost"`
	Status         RedemptionStatus   `json:"status"`
	PointTxID      *string            `json:"point_tx_id"`
	FailureReason  *string            `json:"failure_reason"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
}

type Voucher struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	PointCost   pgtype.Numeric     `json:"point_cost"`
	Stock       int32              `json:"stock"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
