// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voucher.sql

package rewarddb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRedemption = `-- name: CancelRedemption :one
UPDATE redemptions
SET status         = 'cancelled',
    failure_reason = $2,
    cancelled_at   = NOW()
WHERE id = $1
RETURNING id, voucher_id, user_id, point_cost, status, point_tx_id, failure_reason, idempotency_key, created_at, completed_at, cancelled_at
`

type CancelRedemptionParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason *string     `json:"failure_reason"`
}

func (q *Queries) CancelRedemption(ctx context.Context, arg CancelRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, cancelRedemption, arg.ID, arg.FailureReason)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.PointCost,
		&i.Status,
		&i.PointTxID,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const completeRedemption = `-- name: CompleteRedemption :one
UPDATE redemptions
SET status       = 'completed',
    point_tx_id  = $2,
    completed_at = NOW()
WHERE id = $1
RETURNING id, voucher_id, user_id, point_cost, status, point_tx_id, failure_reason, idempotency_key, created_at, completed_at, cancelled_at
`

type CompleteRedemptionParams struct {
	ID        pgtype.UUID `json:"id"`
	PointTxID *string     `json:"point_tx_id"`
}

func (q *Queries) CompleteRedemption(ctx context.Context, arg CompleteRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, completeRedemption, arg.ID, arg.PointTxID)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.PointCost,
		&i.Status,
		&i.PointTxID,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRedemptionByIdempotencyKey = `-- name: GetRedemptionByIdempotencyKey :one
SELECT id, voucher_id, user_id, point_cost, status, point_tx_id, failure_reason, idempotency_key, created_at, completed_at, cancelled_at FROM redemptions WHERE idempotency_key = $1
`

func (q *Queries) GetRedemptionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Redemption, error) {
	row := q.db.QueryRow(ctx, getRedemptionByIdempotencyKey, idempotencyKey)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.PointCost,
		&i.Status,
		&i.PointTxID,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT id, code, title, description, point_cost, stock, is_active, created_at, updated_at FROM vouchers WHERE id = $1
`

func (q *Queries) GetVoucherByID(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByID, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointCost,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPendingRedemption = `-- name: InsertPendingRedemption :one
INSERT INTO redemptions (voucher_id, user_id, point_cost, idempotency_key)
VALUES ($1, $2, $3, $4)
RETURNING id, voucher_id, user_id, point_cost, status, point_tx_id, failure_reason, idempotency_key, created_at, completed_at, cancelled_at
`

type InsertPendingRedemptionParams struct {
	VoucherID      pgtype.UUID    `json:"voucher_id"`
	UserID         pgtype.UUID    `json:"user_id"`
	PointCost      pgtype.Numeric `json:"point_cost"`
	IdempotencyKey string         `json:"idempotency_key"`
}

func (q *Queries) InsertPendingRedemption(ctx context.Context, arg InsertPendingRedemptionParams) (Redemption, error) {
	row := q.db.QueryRow(ctx, insertPendingRedemption,
		arg.VoucherID,
		arg.UserID,
		arg.PointCost,
		arg.IdempotencyKey,
	)
	var i Redemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.PointCost,
		&i.Status,
		&i.PointTxID,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listActiveVouchers = `-- name: ListActiveVouchers :many
SELECT id, code, title, description, point_cost, stock, is_active, created_at, updated_at
FROM vouchers
WHERE is_active = TRUE
ORDER BY point_cost ASC
LIMIT $1
`

func (q *Queries) ListActiveVouchers(ctx context.Context, limit int32) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listActiveVouchers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.PointCost,
			&i.Stock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllVouchers = `-- name: ListAllVouchers :many
SELECT id, code, title, description, point_cost, stock, is_active, created_at, updated_at
FROM vouchers
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAllVouchers(ctx context.Context, limit int32) ([]Voucher, error) {
	rows, err := q.db.Query(ctx, listAllVouchers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Voucher{}
	for rows.Next() {
		var i Voucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.PointCost,
			&i.Stock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseVoucherStock = `-- name: ReleaseVoucherStock :one
UPDATE vouchers
SET stock = stock + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, title, description, point_cost, stock, is_active, created_at, updated_at
`

// Compensation: hoàn 1 đơn vị kho khi Point Service từ chối trừ điểm.
func (q *Queries) ReleaseVoucherStock(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, releaseVoucherStock, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointCost,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveVoucherStock = `-- name: ReserveVoucherStock :one
UPDATE vouchers
SET stock = stock - 1,
    updated_at = NOW()
WHERE id = $1 AND stock > 0 AND is_active = TRUE
RETURNING id, code, title, description, point_cost, stock, is_active, created_at, updated_at
`

// Atomic decrement: chỉ trừ kho khi còn hàng & voucher đang active.
// 0 dòng cập nhật ⇒ sqlc trả pgx.ErrNoRows ⇒ saga abort sớm.
func (q *Queries) ReserveVoucherStock(ctx context.Context, id pgtype.UUID) (Voucher, error) {
	row := q.db.QueryRow(ctx, reserveVoucherStock, id)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.PointCost,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
