// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.js"
// @generated from file ecopoint/booking/v1/booking.proto (package ecopoint.booking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CollectorAcceptBookingRequest, CollectorAcceptBookingResponse, CollectorVerifyBookingRequest, CollectorVerifyBookingResponse, CreateBookingRequest, CreateBookingResponse, DriverCompleteBookingRequest, DriverCompleteBookingResponse, ListBookingsRequest, ListBookingsResponse, ListMyBookingsRequest, ListPendingNearbyRequest } from "./booking_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ecopoint.booking.v1.BookingService
 */
export const BookingService = {
  typeName: "ecopoint.booking.v1.BookingService",
  methods: {
    /**
     * User tạo đơn — server tự sinh PIN 4 số (TTL 10 phút) trả về cho mobile.
     *
     * @generated from rpc ecopoint.booking.v1.BookingService.CreateBooking
     */
    createBooking: {
      name: "CreateBooking",
      I: CreateBookingRequest,
      O: CreateBookingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Vựa (Station) nhận đơn → service tự gọi Point.DeductFee 20 EP.
     * Fail (thiếu số dư) → trả lỗi, đơn vẫn PENDING.
     *
     * @generated from rpc ecopoint.booking.v1.BookingService.CollectorAcceptBooking
     */
    collectorAcceptBooking: {
      name: "CollectorAcceptBooking",
      I: CollectorAcceptBookingRequest,
      O: CollectorAcceptBookingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Driver chốt tại nhà khách: chụp ảnh cân + nhập PIN từ User. Server
     * validate PIN + TTL, đổi status DELIVERED_TO_STATION, gọi
     * Point.IssuePendingReward 2 lần (User + Driver).
     *
     * @generated from rpc ecopoint.booking.v1.BookingService.DriverCompleteBooking
     */
    driverCompleteBooking: {
      name: "DriverCompleteBooking",
      I: DriverCompleteBookingRequest,
      O: DriverCompleteBookingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Vựa cân lại, thực thi Quyền Phủ Quyết (Master Doc §4.1):
     *   |lệch| ≤ 10%  → RECONCILED, ConfirmReward cả 2.
     *   |lệch| >  10% → CANCELLED, CancelReward + DeductTrustScore(20) cả 2.
     *
     * @generated from rpc ecopoint.booking.v1.BookingService.CollectorVerifyBooking
     */
    collectorVerifyBooking: {
      name: "CollectorVerifyBooking",
      I: CollectorVerifyBookingRequest,
      O: CollectorVerifyBookingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.booking.v1.BookingService.ListMyBookings
     */
    listMyBookings: {
      name: "ListMyBookings",
      I: ListMyBookingsRequest,
      O: ListBookingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.booking.v1.BookingService.ListPendingNearby
     */
    listPendingNearby: {
      name: "ListPendingNearby",
      I: ListPendingNearbyRequest,
      O: ListBookingsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc ecopoint.booking.v1.BookingService.ListBookings
     */
    listBookings: {
      name: "ListBookings",
      I: ListBookingsRequest,
      O: ListBookingsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

