// @generated by protoc-gen-es v1.10.0 with parameter "target=ts,import_extension=.js,ts_nocheck=false"
// @generated from file ecopoint/booking/v1/booking.proto (package ecopoint.booking.v1, syntax proto3)
/* eslint-disable */

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { Decimal } from "../../common/v1/common_pb.js";

/**
 * @generated from enum ecopoint.booking.v1.BookingStatus
 */
export enum BookingStatus {
  /**
   * @generated from enum value: BOOKING_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BOOKING_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: BOOKING_STATUS_ACCEPTED = 2;
   */
  ACCEPTED = 2,

  /**
   * @generated from enum value: BOOKING_STATUS_COLLECTING = 3;
   */
  COLLECTING = 3,

  /**
   * @generated from enum value: BOOKING_STATUS_COMPLETED = 4;
   */
  COMPLETED = 4,

  /**
   * @generated from enum value: BOOKING_STATUS_CANCELLED = 5;
   */
  CANCELLED = 5,

  /**
   * V1.3 — Vựa arbitration states.
   *
   * @generated from enum value: BOOKING_STATUS_DELIVERED_TO_STATION = 6;
   */
  DELIVERED_TO_STATION = 6,

  /**
   * @generated from enum value: BOOKING_STATUS_RECONCILED = 7;
   */
  RECONCILED = 7,
}
// Retrieve enum metadata with: proto3.getEnumType(BookingStatus)
proto3.util.setEnumType(BookingStatus, "ecopoint.booking.v1.BookingStatus", [
  { no: 0, name: "BOOKING_STATUS_UNSPECIFIED" },
  { no: 1, name: "BOOKING_STATUS_PENDING" },
  { no: 2, name: "BOOKING_STATUS_ACCEPTED" },
  { no: 3, name: "BOOKING_STATUS_COLLECTING" },
  { no: 4, name: "BOOKING_STATUS_COMPLETED" },
  { no: 5, name: "BOOKING_STATUS_CANCELLED" },
  { no: 6, name: "BOOKING_STATUS_DELIVERED_TO_STATION" },
  { no: 7, name: "BOOKING_STATUS_RECONCILED" },
]);

/**
 * @generated from enum ecopoint.booking.v1.MaterialType
 */
export enum MaterialType {
  /**
   * @generated from enum value: MATERIAL_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MATERIAL_TYPE_PAPER = 1;
   */
  PAPER = 1,

  /**
   * @generated from enum value: MATERIAL_TYPE_PLASTIC = 2;
   */
  PLASTIC = 2,

  /**
   * @generated from enum value: MATERIAL_TYPE_METAL = 3;
   */
  METAL = 3,

  /**
   * @generated from enum value: MATERIAL_TYPE_MIXED = 4;
   */
  MIXED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(MaterialType)
proto3.util.setEnumType(MaterialType, "ecopoint.booking.v1.MaterialType", [
  { no: 0, name: "MATERIAL_TYPE_UNSPECIFIED" },
  { no: 1, name: "MATERIAL_TYPE_PAPER" },
  { no: 2, name: "MATERIAL_TYPE_PLASTIC" },
  { no: 3, name: "MATERIAL_TYPE_METAL" },
  { no: 4, name: "MATERIAL_TYPE_MIXED" },
]);

/**
 * @generated from message ecopoint.booking.v1.Booking
 */
export class Booking extends Message<Booking> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId = "";

  /**
   * @generated from field: string collector_id = 3;
   */
  collectorId = "";

  /**
   * @generated from field: ecopoint.booking.v1.BookingStatus status = 4;
   */
  status = BookingStatus.UNSPECIFIED;

  /**
   * @generated from field: string address = 5;
   */
  address = "";

  /**
   * @generated from field: double longitude = 6;
   */
  longitude = 0;

  /**
   * @generated from field: double latitude = 7;
   */
  latitude = 0;

  /**
   * @generated from field: ecopoint.common.v1.Decimal estimated_kg = 8;
   */
  estimatedKg?: Decimal;

  /**
   * @generated from field: string note = 9;
   */
  note = "";

  /**
   * @generated from field: ecopoint.booking.v1.MaterialType material_type = 10;
   */
  materialType = MaterialType.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp scheduled_at = 11;
   */
  scheduledAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 12;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 13;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: double distance_m = 14;
   */
  distanceM = 0;

  /**
   * V1.3 fields:
   *
   * set khi >= ACCEPTED
   *
   * @generated from field: string station_id = 15;
   */
  stationId = "";

  /**
   * chỉ trả về cho customer khi CreateBooking
   *
   * @generated from field: string pin_code = 16;
   */
  pinCode = "";

  /**
   * @generated from field: google.protobuf.Timestamp pin_expired_at = 17;
   */
  pinExpiredAt?: Timestamp;

  /**
   * Driver chốt tại nhà khách
   *
   * @generated from field: double driver_weight = 18;
   */
  driverWeight = 0;

  /**
   * Vựa cân lại
   *
   * @generated from field: double collector_weight = 19;
   */
  collectorWeight = 0;

  /**
   * ảnh mặt cân điện tử
   *
   * @generated from field: string proof_image_url = 20;
   */
  proofImageUrl = "";

  constructor(data?: PartialMessage<Booking>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.Booking";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "collector_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "enum", T: proto3.getEnumType(BookingStatus) },
    { no: 5, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 8, name: "estimated_kg", kind: "message", T: Decimal },
    { no: 9, name: "note", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "material_type", kind: "enum", T: proto3.getEnumType(MaterialType) },
    { no: 11, name: "scheduled_at", kind: "message", T: Timestamp },
    { no: 12, name: "created_at", kind: "message", T: Timestamp },
    { no: 13, name: "updated_at", kind: "message", T: Timestamp },
    { no: 14, name: "distance_m", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 15, name: "station_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 16, name: "pin_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 17, name: "pin_expired_at", kind: "message", T: Timestamp },
    { no: 18, name: "driver_weight", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 19, name: "collector_weight", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 20, name: "proof_image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Booking {
    return new Booking().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Booking {
    return new Booking().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Booking {
    return new Booking().fromJsonString(jsonString, options);
  }

  static equals(a: Booking | PlainMessage<Booking> | undefined, b: Booking | PlainMessage<Booking> | undefined): boolean {
    return proto3.util.equals(Booking, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CreateBookingRequest
 */
export class CreateBookingRequest extends Message<CreateBookingRequest> {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId = "";

  /**
   * @generated from field: string address = 2;
   */
  address = "";

  /**
   * @generated from field: double longitude = 3;
   */
  longitude = 0;

  /**
   * @generated from field: double latitude = 4;
   */
  latitude = 0;

  /**
   * @generated from field: ecopoint.common.v1.Decimal estimated_kg = 5;
   */
  estimatedKg?: Decimal;

  /**
   * @generated from field: string note = 6;
   */
  note = "";

  /**
   * @generated from field: ecopoint.booking.v1.MaterialType material_type = 7;
   */
  materialType = MaterialType.UNSPECIFIED;

  /**
   * @generated from field: google.protobuf.Timestamp scheduled_at = 8;
   */
  scheduledAt?: Timestamp;

  constructor(data?: PartialMessage<CreateBookingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CreateBookingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "estimated_kg", kind: "message", T: Decimal },
    { no: 6, name: "note", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "material_type", kind: "enum", T: proto3.getEnumType(MaterialType) },
    { no: 8, name: "scheduled_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBookingRequest {
    return new CreateBookingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBookingRequest {
    return new CreateBookingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBookingRequest {
    return new CreateBookingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBookingRequest | PlainMessage<CreateBookingRequest> | undefined, b: CreateBookingRequest | PlainMessage<CreateBookingRequest> | undefined): boolean {
    return proto3.util.equals(CreateBookingRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CreateBookingResponse
 */
export class CreateBookingResponse extends Message<CreateBookingResponse> {
  /**
   * @generated from field: ecopoint.booking.v1.Booking booking = 1;
   */
  booking?: Booking;

  constructor(data?: PartialMessage<CreateBookingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CreateBookingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking", kind: "message", T: Booking },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBookingResponse {
    return new CreateBookingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBookingResponse {
    return new CreateBookingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBookingResponse {
    return new CreateBookingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBookingResponse | PlainMessage<CreateBookingResponse> | undefined, b: CreateBookingResponse | PlainMessage<CreateBookingResponse> | undefined): boolean {
    return proto3.util.equals(CreateBookingResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CollectorAcceptBookingRequest
 */
export class CollectorAcceptBookingRequest extends Message<CollectorAcceptBookingRequest> {
  /**
   * @generated from field: string booking_id = 1;
   */
  bookingId = "";

  /**
   * @generated from field: string station_id = 2;
   */
  stationId = "";

  constructor(data?: PartialMessage<CollectorAcceptBookingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CollectorAcceptBookingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "station_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectorAcceptBookingRequest {
    return new CollectorAcceptBookingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectorAcceptBookingRequest {
    return new CollectorAcceptBookingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectorAcceptBookingRequest {
    return new CollectorAcceptBookingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CollectorAcceptBookingRequest | PlainMessage<CollectorAcceptBookingRequest> | undefined, b: CollectorAcceptBookingRequest | PlainMessage<CollectorAcceptBookingRequest> | undefined): boolean {
    return proto3.util.equals(CollectorAcceptBookingRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CollectorAcceptBookingResponse
 */
export class CollectorAcceptBookingResponse extends Message<CollectorAcceptBookingResponse> {
  /**
   * @generated from field: ecopoint.booking.v1.Booking booking = 1;
   */
  booking?: Booking;

  /**
   * tx_id của DeductFee 20 EP — audit trail.
   *
   * @generated from field: string point_tx_id = 2;
   */
  pointTxId = "";

  constructor(data?: PartialMessage<CollectorAcceptBookingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CollectorAcceptBookingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking", kind: "message", T: Booking },
    { no: 2, name: "point_tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectorAcceptBookingResponse {
    return new CollectorAcceptBookingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectorAcceptBookingResponse {
    return new CollectorAcceptBookingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectorAcceptBookingResponse {
    return new CollectorAcceptBookingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CollectorAcceptBookingResponse | PlainMessage<CollectorAcceptBookingResponse> | undefined, b: CollectorAcceptBookingResponse | PlainMessage<CollectorAcceptBookingResponse> | undefined): boolean {
    return proto3.util.equals(CollectorAcceptBookingResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.DriverCompleteBookingRequest
 */
export class DriverCompleteBookingRequest extends Message<DriverCompleteBookingRequest> {
  /**
   * @generated from field: string booking_id = 1;
   */
  bookingId = "";

  /**
   * @generated from field: string driver_id = 2;
   */
  driverId = "";

  /**
   * @generated from field: string pin_code = 3;
   */
  pinCode = "";

  /**
   * @generated from field: string proof_image_url = 4;
   */
  proofImageUrl = "";

  /**
   * kg, có thể lẻ
   *
   * @generated from field: double driver_weight = 5;
   */
  driverWeight = 0;

  constructor(data?: PartialMessage<DriverCompleteBookingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.DriverCompleteBookingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "driver_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "pin_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "proof_image_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "driver_weight", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DriverCompleteBookingRequest {
    return new DriverCompleteBookingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DriverCompleteBookingRequest {
    return new DriverCompleteBookingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DriverCompleteBookingRequest {
    return new DriverCompleteBookingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DriverCompleteBookingRequest | PlainMessage<DriverCompleteBookingRequest> | undefined, b: DriverCompleteBookingRequest | PlainMessage<DriverCompleteBookingRequest> | undefined): boolean {
    return proto3.util.equals(DriverCompleteBookingRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.DriverCompleteBookingResponse
 */
export class DriverCompleteBookingResponse extends Message<DriverCompleteBookingResponse> {
  /**
   * @generated from field: ecopoint.booking.v1.Booking booking = 1;
   */
  booking?: Booking;

  /**
   * 2 tx pending: cấp điểm cho User (kg*10) + Driver (flat 20).
   *
   * @generated from field: string user_point_tx_id = 2;
   */
  userPointTxId = "";

  /**
   * @generated from field: string driver_point_tx_id = 3;
   */
  driverPointTxId = "";

  constructor(data?: PartialMessage<DriverCompleteBookingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.DriverCompleteBookingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking", kind: "message", T: Booking },
    { no: 2, name: "user_point_tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "driver_point_tx_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DriverCompleteBookingResponse {
    return new DriverCompleteBookingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DriverCompleteBookingResponse {
    return new DriverCompleteBookingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DriverCompleteBookingResponse {
    return new DriverCompleteBookingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DriverCompleteBookingResponse | PlainMessage<DriverCompleteBookingResponse> | undefined, b: DriverCompleteBookingResponse | PlainMessage<DriverCompleteBookingResponse> | undefined): boolean {
    return proto3.util.equals(DriverCompleteBookingResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CollectorVerifyBookingRequest
 */
export class CollectorVerifyBookingRequest extends Message<CollectorVerifyBookingRequest> {
  /**
   * @generated from field: string booking_id = 1;
   */
  bookingId = "";

  /**
   * @generated from field: double collector_weight = 2;
   */
  collectorWeight = 0;

  /**
   * station member user_id
   *
   * @generated from field: string verified_by = 3;
   */
  verifiedBy = "";

  constructor(data?: PartialMessage<CollectorVerifyBookingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CollectorVerifyBookingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "collector_weight", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "verified_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectorVerifyBookingRequest {
    return new CollectorVerifyBookingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectorVerifyBookingRequest {
    return new CollectorVerifyBookingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectorVerifyBookingRequest {
    return new CollectorVerifyBookingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CollectorVerifyBookingRequest | PlainMessage<CollectorVerifyBookingRequest> | undefined, b: CollectorVerifyBookingRequest | PlainMessage<CollectorVerifyBookingRequest> | undefined): boolean {
    return proto3.util.equals(CollectorVerifyBookingRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.CollectorVerifyBookingResponse
 */
export class CollectorVerifyBookingResponse extends Message<CollectorVerifyBookingResponse> {
  /**
   * @generated from field: ecopoint.booking.v1.Booking booking = 1;
   */
  booking?: Booking;

  /**
   * true = pass, false = bị phạt
   *
   * @generated from field: bool reconciled = 2;
   */
  reconciled = false;

  /**
   * |collector - driver| / driver * 100
   *
   * @generated from field: double deviation_pct = 3;
   */
  deviationPct = 0;

  constructor(data?: PartialMessage<CollectorVerifyBookingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.CollectorVerifyBookingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "booking", kind: "message", T: Booking },
    { no: 2, name: "reconciled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "deviation_pct", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CollectorVerifyBookingResponse {
    return new CollectorVerifyBookingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CollectorVerifyBookingResponse {
    return new CollectorVerifyBookingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CollectorVerifyBookingResponse {
    return new CollectorVerifyBookingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CollectorVerifyBookingResponse | PlainMessage<CollectorVerifyBookingResponse> | undefined, b: CollectorVerifyBookingResponse | PlainMessage<CollectorVerifyBookingResponse> | undefined): boolean {
    return proto3.util.equals(CollectorVerifyBookingResponse, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.ListMyBookingsRequest
 */
export class ListMyBookingsRequest extends Message<ListMyBookingsRequest> {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId = "";

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListMyBookingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.ListMyBookingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "customer_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListMyBookingsRequest {
    return new ListMyBookingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListMyBookingsRequest {
    return new ListMyBookingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListMyBookingsRequest {
    return new ListMyBookingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListMyBookingsRequest | PlainMessage<ListMyBookingsRequest> | undefined, b: ListMyBookingsRequest | PlainMessage<ListMyBookingsRequest> | undefined): boolean {
    return proto3.util.equals(ListMyBookingsRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.ListBookingsRequest
 */
export class ListBookingsRequest extends Message<ListBookingsRequest> {
  /**
   * @generated from field: ecopoint.booking.v1.BookingStatus status = 1;
   */
  status = BookingStatus.UNSPECIFIED;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListBookingsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.ListBookingsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "status", kind: "enum", T: proto3.getEnumType(BookingStatus) },
    { no: 2, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBookingsRequest {
    return new ListBookingsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBookingsRequest {
    return new ListBookingsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBookingsRequest {
    return new ListBookingsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListBookingsRequest | PlainMessage<ListBookingsRequest> | undefined, b: ListBookingsRequest | PlainMessage<ListBookingsRequest> | undefined): boolean {
    return proto3.util.equals(ListBookingsRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.ListPendingNearbyRequest
 */
export class ListPendingNearbyRequest extends Message<ListPendingNearbyRequest> {
  /**
   * @generated from field: double longitude = 1;
   */
  longitude = 0;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude = 0;

  /**
   * @generated from field: int32 limit = 3;
   */
  limit = 0;

  constructor(data?: PartialMessage<ListPendingNearbyRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.ListPendingNearbyRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListPendingNearbyRequest {
    return new ListPendingNearbyRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListPendingNearbyRequest {
    return new ListPendingNearbyRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListPendingNearbyRequest {
    return new ListPendingNearbyRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListPendingNearbyRequest | PlainMessage<ListPendingNearbyRequest> | undefined, b: ListPendingNearbyRequest | PlainMessage<ListPendingNearbyRequest> | undefined): boolean {
    return proto3.util.equals(ListPendingNearbyRequest, a, b);
  }
}

/**
 * @generated from message ecopoint.booking.v1.ListBookingsResponse
 */
export class ListBookingsResponse extends Message<ListBookingsResponse> {
  /**
   * @generated from field: repeated ecopoint.booking.v1.Booking bookings = 1;
   */
  bookings: Booking[] = [];

  constructor(data?: PartialMessage<ListBookingsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "ecopoint.booking.v1.ListBookingsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "bookings", kind: "message", T: Booking, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBookingsResponse {
    return new ListBookingsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBookingsResponse {
    return new ListBookingsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBookingsResponse {
    return new ListBookingsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListBookingsResponse | PlainMessage<ListBookingsResponse> | undefined, b: ListBookingsResponse | PlainMessage<ListBookingsResponse> | undefined): boolean {
    return proto3.util.equals(ListBookingsResponse, a, b);
  }
}

